# -*- coding: utf-8 -*-
"""adaboost_vs_xgboost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RrOly5Dgn7bRWzlBRAp983--WQ-ncSV
"""

# ─── Temel veri işleme kütüphaneleri ───────────────────────────────────────
import numpy as np          # Sayısal hesaplamalar (dizi işlemleri, lineer cebir)
import pandas as pd         # Tablo (DataFrame) yapısında veri işleme
import matplotlib.pyplot as plt  # Grafik çizimi
import seaborn as sns       # matplotlib üzerine kurulu, daha şık görselleştirme
import warnings
warnings.filterwarnings('ignore')  # Gereksiz uyarıları gizle

# ─── Scikit-learn araçları ──────────────────────────────────────────────────
from sklearn.datasets import make_classification, load_breast_cancer
# load_breast_cancer : 569 örnek, 30 özellik içeren gerçek tıbbi veri seti

from sklearn.model_selection import train_test_split, cross_val_score, learning_curve
# train_test_split : veriyi eğitim / test olarak böler
# cross_val_score  : k-fold çapraz doğrulama skoru
# learning_curve   : farklı eğitim boyutlarında performans eğrisi

from sklearn.ensemble import AdaBoostClassifier
# AdaBoost sınıflandırıcı — sklearn içinde hazır gelir

from sklearn.tree import DecisionTreeClassifier
# AdaBoost'un zayıf öğrenicisi olarak kullanılacak karar ağacı

from sklearn.preprocessing import StandardScaler
# Özellikleri ortalaması 0, std'si 1 olacak şekilde ölçekler

from sklearn.metrics import (
    accuracy_score,         # Doğru tahmin oranı
    classification_report,  # Precision / Recall / F1 özet tablosu
    confusion_matrix,       # Hangi sınıf hangisiyle karıştırıldı?
    roc_auc_score,          # ROC eğrisinin altındaki alan (0.5=rastgele, 1=mükemmel)
    roc_curve,              # FPR ve TPR değerleri (ROC grafiği için)
    f1_score,               # Precision ve Recall'ın harmonik ortalaması
    precision_score,        # TP / (TP + FP) — "Tahmin ettiklerimin kaçı doğru?"
    recall_score            # TP / (TP + FN) — "Gerçeklerin kaçını yakaladım?"
)

import xgboost as xgb      # XGBoost kütüphanesi (pip install xgboost)
import time                 # Eğitim süresi ölçümü için

# ─── Görsel ayarlar ─────────────────────────────────────────────────────────
plt.rcParams['figure.figsize'] = (12, 5)      # Varsayılan grafik boyutu
plt.rcParams['font.size'] = 12                # Varsayılan yazı boyutu
plt.style.use('seaborn-v0_8-whitegrid')       # Beyaz ızgara temalı stil

print('✅ Tüm kütüphaneler başarıyla yüklendi!')
print(f'   XGBoost versiyonu: {xgb.__version__}')

# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "Churn_Modelling.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "shrutimechlearn/churn-modelling",
  file_path
)

print("Veri başarıyla yüklendi!")
print("Satır ve sütun sayısı:", df.shape)
print(df.head())

# 1. Veriyi temizle: Gereksiz sütunları at (RowNumber, CustomerId, Surname model için anlamsız)
X = df.drop(['Exited', 'RowNumber', 'CustomerId', 'Surname'], axis=1, errors='ignore')
y = df['Exited'] # Hedef sütunumuz 'Exited' (1=Ayrıldı, 0=Kaldı)

# 2. Kategorik değişkenleri sayısal hale getir (Geography ve Gender sütunları)
# One-Hot Encoding: 'France', 'Spain' gibi değerleri 0 ve 1'lere ayırır.
X = pd.get_dummies(X, drop_first=True)

# 3. Eğitim / Test olarak böl
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y  # Sınıf dağılımını koru
)

print('📋 Veri Seti Bilgileri')
print('='*40)
print(f'Özellik sayısı  : {X.shape[1]}')
print(f'Örnek sayısı    : {X.shape[0]}')
print(f'Sınıf dağılımı  : {dict(y.value_counts())}')
print(f'  0 = Kaldı (No)  : {sum(y==0)}')
print(f'  1 = Ayrıldı (Yes): {sum(y==1)}')
print()
print(f'Eğitim seti: {X_train.shape[0]} örnek')
print(f'Test seti  : {X_test.shape[0]} örnek')
X.head()  # İlk 5 satırı göster

# ─── Veri setini görselleştir ───────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Sol grafik: Sınıf dağılımını pasta grafikle göster (Kaldı vs Ayrıldı)
counts = y.value_counts()
labels = ['Kaldı (No)', 'Ayrıldı (Yes)']
colors = ['#2ecc71', '#e74c3c'] # Kaldı=Yeşil, Ayrıldı=Kırmızı
axes[0].pie(
    counts,
    labels=labels,
    colors=colors,
    autopct='%1.1f%%',
    startangle=90,
    shadow=True,
    textprops={'fontsize': 12}
)
axes[0].set_title('Sınıf Dağılımı', fontsize=14, fontweight='bold')

# Sağ grafik: 'Age' (Yaş) özelliğinin iki sınıfa göre histogramı
# (Senin verinde 'Age' sütunu olduğu için bunu seçtik)
axes[1].hist(X['Age'][y==0], alpha=0.5, label='Kaldı', color='#2ecc71', bins=20)
axes[1].hist(X['Age'][y==1], alpha=0.5, label='Ayrıldı', color='#e74c3c', bins=20)

axes[1].set_title('Dağılım: Yaş (Age)', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Yaş')
axes[1].set_ylabel('Müşteri Sayısı')
axes[1].legend()

plt.tight_layout()
plt.suptitle('Bank Customer Churn - Veri Analizi', fontsize=16, fontweight='bold', y=1.02)
plt.show()

## 🔴 7. AdaBoost Modeli

print('🔴 ADABOOST MODELİ EĞİTİLİYOR...')
print('='*45)

# ─── AdaBoost modelini tanımla ──────────────────────────────────────────────
ada_model = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1),
    # Zayıf öğrenici olarak 'Decision Stump' kullanıyoruz.
    # max_depth=1 → yalnızca tek bir karar dalı; kasıtlı olarak zayıf tutulur.
    # Güçlü bir ağaç seçmek AdaBoost'un dengeleme mantığını bozar.

    n_estimators=100,
    # Kaç tane zayıf öğrenici oluşturulacak?
    # Artırmak genellikle doğruluğu iyileştirir ama bir noktadan sonra plateau oluşur.

    learning_rate=0.1,
    # Her zayıf öğrenicinin final tahmine katkısını küçülten çarpan.
    # Küçük değer → daha yavaş öğrenme ama daha iyi genelleme.
    # learning_rate ile n_estimators arasında ters orantı vardır.

    algorithm='SAMME',
    # 'SAMME'  : sınıf etiketleri (hard vote) kullanır — sklearn>=1.2'de varsayılan.
    # 'SAMME.R': olasılık tahmini kullanır, genellikle daha iyi ama yavaş.

    random_state=42         # Tekrar üretilebilir sonuçlar için sabit tohum
)

# ─── Eğitim ─────────────────────────────────────────────────────────────────
start = time.time()                         # Saat başlatılıyor
ada_model.fit(X_train, y_train)             # Modeli eğitim verisiyle öğret
ada_time = time.time() - start              # Geçen süreyi hesapla

# ─── Tahmin ─────────────────────────────────────────────────────────────────
ada_pred = ada_model.predict(X_test)
# predict() → her örnek için sınıf etiketi döner (0 veya 1)

ada_prob = ada_model.predict_proba(X_test)[:, 1]
# predict_proba() → her örnek için [P(sınıf=0), P(sınıf=1)] döner.
# [:, 1] → sadece pozitif sınıf (Benign) olasılığını al → ROC için gerekli

# ─── Performans metrikleri ───────────────────────────────────────────────────
ada_acc    = accuracy_score(y_test, ada_pred)
# Doğruluk = doğru tahmin sayısı / toplam tahmin sayısı

ada_auc    = roc_auc_score(y_test, ada_prob)
# ROC eğrisinin altındaki alan; 0.5=rastgele, 1.0=mükemmel

ada_f1     = f1_score(y_test, ada_pred)
# F1 = 2 * (Precision * Recall) / (Precision + Recall)
# Dengesiz veri setlerinde accuracy'den daha güvenilir

ada_prec   = precision_score(y_test, ada_pred)
# Precision: "Benign" dediğimizin gerçekten Benign olma oranı

ada_recall = recall_score(y_test, ada_pred)
# Recall (Sensitivity): Gerçek Benign'lerin ne kadarını yakaladık?

print(f'✅ Eğitim Süresi   : {ada_time:.4f} sn')
print(f'📊 Doğruluk (Acc)  : {ada_acc:.4f}  ({ada_acc*100:.2f}%)')
print(f'📊 AUC-ROC         : {ada_auc:.4f}')
print(f'📊 F1 Skoru        : {ada_f1:.4f}')
print(f'📊 Precision       : {ada_prec:.4f}')
print(f'📊 Recall          : {ada_recall:.4f}')
print()
print('📋 Detaylı Rapor:')
print(classification_report(y_test, ada_pred, target_names=['Kaldı (No)', 'Ayrıldı (Yes)']))

# ─── n_estimators'a göre performans analizi ─────────────────────────────────
# Kaç tane zayıf öğrenici kullanılırsa en iyi sonuç alınır?
# 1'den 200'e kadar 10'ar adımla deniyoruz.

n_estimators_range = range(1, 201, 10)
ada_train_scores = []   # Her n için eğitim doğruluğunu saklayacak liste
ada_test_scores  = []   # Her n için test doğruluğunu saklayacak liste

for n in n_estimators_range:
    m = AdaBoostClassifier(
        estimator=DecisionTreeClassifier(max_depth=1),
        n_estimators=n,
        learning_rate=0.1,
        algorithm='SAMME',
        random_state=42
    )
    m.fit(X_train, y_train)   # Her n için ayrı model eğit
    ada_train_scores.append(accuracy_score(y_train, m.predict(X_train)))
    ada_test_scores.append(accuracy_score(y_test,  m.predict(X_test)))

plt.figure(figsize=(12, 5))

# '-o' : noktalı çizgi (o=daire marker, - = düz çizgi)
plt.plot(n_estimators_range, ada_train_scores, 'r-o', markersize=4,
         label='Eğitim Doğruluğu', linewidth=2)

# '--s' : kesik çizgi (s=kare marker, --=kesikli)
plt.plot(n_estimators_range, ada_test_scores, 'r--s', markersize=4,
         label='Test Doğruluğu', linewidth=2)

# Eğitim ve test eğrileri birbirinden uzaklaşıyorsa → OVERFITTING sinyali

plt.xlabel('Zayıf Öğrenici Sayısı (n_estimators)', fontsize=12)
plt.ylabel('Doğruluk', fontsize=12)
plt.title('🔴 AdaBoost — n_estimators vs Doğruluk', fontsize=14, fontweight='bold')
plt.legend(fontsize=11)
plt.ylim(0.75, 0.90)
plt.tight_layout()
plt.show()

## 🟢 8. XGBoost Modeli

print('🟢 XGBOOST MODELİ EĞİTİLİYOR...')
print('='*45)

# ─── XGBoost modelini tanımla ───────────────────────────────────────────────
xgb_model = xgb.XGBClassifier(
    n_estimators=100,
    # Toplam ağaç (iterasyon) sayısı.
    # Her iterasyonda bir ağaç eklenir, bir öncekinin hatasını düzeltir.

    max_depth=3,
    # Her ağacın maksimum derinliği.
    # Derinlik arttıkça model karmaşıklaşır → overfitting riski.
    # Genellikle 3-6 arası iyi sonuç verir.

    learning_rate=0.1,
    # Eta (η) olarak da bilinir.
    # Her yeni ağacın katkısını bu katsayıyla küçültür.
    # Küçük lr + fazla ağaç → daha iyi ama daha yavaş.

    subsample=0.8,
    # Her ağacı eğitirken eğitim verisinin %80'ini rastgele seç.
    # Kalan %20 görmezden gelinir → varyansı düşürür (Random Forest'taki gibi).

    colsample_bytree=0.8,
    # Her ağaç için özelliklerin %80'ini rastgele kullan.
    # Özellikler arasındaki korelasyonu kırar, modeli güçlendirir.

    reg_alpha=0.1,
    # L1 (Lasso) regularizasyon katsayısı.
    # Bazı ağırlıkları sıfıra iter → seyrek (sparse) model → özellik seçimi etkisi.

    reg_lambda=1.0,
    # L2 (Ridge) regularizasyon katsayısı.
    # Ağırlıkları küçük tutar → overfitting'i önler.
    # XGBoost'ta varsayılan değer 1.0'dır.

    use_label_encoder=False,
    # Eski XGBoost sürümlerinde etiketleri kodlamak için kullanılırdı.
    # Artık gerekli değil; uyarı mesajını önlemek için False.

    eval_metric='logloss',
    # Eğitim sırasında izlenecek metrik.
    # logloss (log loss): olasılık tahminlerinin kalitesini ölçer.
    # Düştükçe model daha iyi öğreniyor demektir.

    random_state=42,        # Tekrar üretilebilirlik için sabit tohum
    verbosity=0             # 0 = hiç log yazdırma
)

# ─── Eğitim ─────────────────────────────────────────────────────────────────
start = time.time()
xgb_model.fit(
    X_train, y_train,
    eval_set=[(X_train, y_train), (X_test, y_test)],
    # eval_set: her iterasyonda bu veri setlerinde logloss hesapla.
    # validation_0 → eğitim seti, validation_1 → test seti.
    # Sonradan evals_result() ile bu değerlere erişip grafik çizebiliriz.
    verbose=False           # İterasyon başına log yazdırma
)
xgb_time = time.time() - start

# ─── Tahmin ─────────────────────────────────────────────────────────────────
xgb_pred = xgb_model.predict(X_test)
# Sınıf etiketi tahmini: 0 veya 1

xgb_prob = xgb_model.predict_proba(X_test)[:, 1]
# Pozitif sınıf (Benign=1) olasılıkları → AUC-ROC hesabı için gerekli

# ─── Performans metrikleri ───────────────────────────────────────────────────
xgb_acc    = accuracy_score(y_test, xgb_pred)
xgb_auc    = roc_auc_score(y_test, xgb_prob)
xgb_f1     = f1_score(y_test, xgb_pred)
xgb_prec   = precision_score(y_test, xgb_pred)
xgb_recall = recall_score(y_test, xgb_pred)

print(f'✅ Eğitim Süresi   : {xgb_time:.4f} sn')
print(f'📊 Doğruluk (Acc)  : {xgb_acc:.4f}  ({xgb_acc*100:.2f}%)')
print(f'📊 AUC-ROC         : {xgb_auc:.4f}')
print(f'📊 F1 Skoru        : {xgb_f1:.4f}')
print(f'📊 Precision       : {xgb_prec:.4f}')
print(f'📊 Recall          : {xgb_recall:.4f}')
print()
print('📋 Detaylı Rapor (Güncellenmiş):')
print(classification_report(y_test, xgb_pred, target_names=['Kaldı (No)', 'Ayrıldı (Yes)']))

# ─── XGBoost: Özellik Önemi + Eğitim Eğrisi ─────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# ── Sol: Özellik Önemi ──────────────────────────────────────────────────────
feat_importance = pd.Series(
    xgb_model.feature_importances_,
    index=X.columns # Burası çok önemli: senin X matrisinin sütun isimleri!
).sort_values(ascending=True).tail(15)
# sort_values(ascending=True): küçükten büyüğe → yatay barda alta koymak için
# .tail(15): sadece en önemli 15 özelliği al

feat_importance.plot(kind='barh', ax=axes[0], color='#2ecc71', edgecolor='white')
axes[0].set_title('🟢 XGBoost — En Önemli 15 Özellik', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Önem Skoru')

# ── Sağ: Eğitim Eğrisi (Log Loss) ──────────────────────────────────────────
results = xgb_model.evals_result()
# evals_result(): fit() sırasında eval_set ile kayıt altına alınan
# her iterasyondaki logloss değerlerini dict olarak döner.
# results['validation_0'] → eğitim seti sonuçları
# results['validation_1'] → test seti sonuçları

axes[1].plot(results['validation_0']['logloss'],
             label='Eğitim', color='#3498db', linewidth=2)
axes[1].plot(results['validation_1']['logloss'],
             label='Test', color='#e74c3c', linewidth=2, linestyle='--')
# Beklenen davranış: her iki eğri de düşmeli.
# Test kaybı düşüp tekrar yükseliyorsa → erken durdurma (early stopping) önerilir.

axes[1].set_title('🟢 XGBoost — Eğitim Eğrisi (Log Loss)', fontsize=13, fontweight='bold')
axes[1].set_xlabel('İterasyon')
axes[1].set_ylabel('Log Loss')
axes[1].legend(fontsize=11)

plt.tight_layout()
plt.show()

## ⚖️ 9. Kapsamlı Karşılaştırma

# ─── Confusion Matrix Karşılaştırması ───────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# zip() ile iki modelin verisi aynı anda işleniyor
for ax, pred, title, color in zip(
    axes,
    [ada_pred, xgb_pred],
    ['🔴 AdaBoost', '🟢 XGBoost'],
    ['Reds', 'Greens']
):
    cm = confusion_matrix(y_test, pred)

    sns.heatmap(
        cm,
        annot=True,
        fmt='d',
        cmap=color,
        ax=ax,
        xticklabels=['Kaldı (No)', 'Ayrıldı (Yes)'], # Güncellendi
        yticklabels=['Kaldı (No)', 'Ayrıldı (Yes)'], # Güncellendi
        linewidths=2,
        linecolor='white',
        annot_kws={'size': 14, 'weight': 'bold'}
    )
    ax.set_title(f'{title}\nConfusion Matrix', fontsize=13, fontweight='bold')
    ax.set_ylabel('Gerçek Sınıf', fontsize=11)
    ax.set_xlabel('Tahmin Edilen Sınıf', fontsize=11)

plt.suptitle('Confusion Matrix Karşılaştırması', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.show()

# ─── ROC Eğrisi + Metrik Bar Grafiği ────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# ── Sol: ROC Eğrisi ──────────────────────────────────────────────────────────
# ROC (Receiver Operating Characteristic):
#   X ekseni → FPR (False Positive Rate = FP / (FP + TN))
#   Y ekseni → TPR (True Positive Rate  = TP / (TP + FN))
# Eşik değeri 0'dan 1'e doğru değiştirilerek farklı FPR/TPR çiftleri elde edilir.
# Sol üst köşeye yakın eğri → daha iyi model.

for prob, label, color, acc, auc in [
    (ada_prob, 'AdaBoost', '#e74c3c', ada_acc, ada_auc),
    (xgb_prob, 'XGBoost',  '#2ecc71', xgb_acc, xgb_auc)
]:
    fpr, tpr, _ = roc_curve(y_test, prob)
    # roc_curve() → farklı eşik değerleri için (fpr, tpr, thresholds) döner
    axes[0].plot(fpr, tpr, color=color, linewidth=2.5,
                 label=f'{label} (AUC={auc:.4f})')

# Çapraz çizgi: AUC=0.5 → tamamen rastgele tahmin yapan model
axes[0].plot([0, 1], [0, 1], 'k--', linewidth=1, label='Rastgele Tahmin')
axes[0].fill_between([0, 1], [0, 1], alpha=0.05, color='gray')
axes[0].set_xlim([0, 1])
axes[0].set_ylim([0, 1.02])
axes[0].set_xlabel('False Positive Rate (FPR)', fontsize=12)
axes[0].set_ylabel('True Positive Rate (TPR)', fontsize=12)
axes[0].set_title('ROC Eğrisi Karşılaştırması', fontsize=14, fontweight='bold')
axes[0].legend(fontsize=11)
axes[0].grid(True, alpha=0.3)

# ── Sağ: Metrik Bar Grafiği ──────────────────────────────────────────────────
metrics    = ['Accuracy', 'AUC-ROC', 'F1 Score', 'Precision', 'Recall']
ada_scores = [ada_acc, ada_auc, ada_f1, ada_prec, ada_recall]
xgb_scores = [xgb_acc, xgb_auc, xgb_f1, xgb_prec, xgb_recall]

x = np.arange(len(metrics))   # [0, 1, 2, 3, 4] → her metrik için x konumu
width = 0.35                   # Her barın genişliği

# İki model için yan yana bar: biri sola (- width/2), biri sağa (+ width/2)
bars1 = axes[1].bar(x - width/2, ada_scores, width, label='AdaBoost',
                     color='#e74c3c', alpha=0.85, edgecolor='white', linewidth=1.5)
bars2 = axes[1].bar(x + width/2, xgb_scores, width, label='XGBoost',
                     color='#2ecc71', alpha=0.85, edgecolor='white', linewidth=1.5)

# Her barın üstüne sayısal değer yaz
for bar in bars1:
    height = bar.get_height()
    axes[1].text(bar.get_x() + bar.get_width()/2., height + 0.01,
                 f'{height:.3f}', ha='center', va='bottom', fontsize=9, fontweight='bold')

for bar in bars2:
    height = bar.get_height()
    axes[1].text(bar.get_x() + bar.get_width()/2., height + 0.01,
                 f'{height:.3f}', ha='center', va='bottom', fontsize=9, fontweight='bold')

axes[1].set_xticks(x)
axes[1].set_xticklabels(metrics, fontsize=11)
axes[1].set_ylabel('Skor', fontsize=12)
axes[1].set_title('Tüm Metrikler Karşılaştırması', fontsize=14, fontweight='bold')
axes[1].legend(fontsize=11)
axes[1].set_ylim(0.0, 1.05)
axes[1].grid(True, axis='y', alpha=0.3)

plt.suptitle('AdaBoost vs XGBoost — Performans Karşılaştırması',
             fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

# ─── 5-Fold Cross Validation ────────────────────────────────────────────────
# Cross validation neden gerekli?
# Tek train/test bölmesi şansa bağlıdır. CV, veriyi 5 farklı şekilde bölerek
# daha güvenilir ve genellenebilir bir performans tahmini verir.

print('🔄 5-Fold Cross Validation Yapılıyor...')
print('='*45)

ada_cv = cross_val_score(ada_model, X, y, cv=5, scoring='accuracy')
# cv=5 : veriyi 5 parçaya böl, her seferinde 1 parça test, 4 parça eğitim
# scoring='accuracy' : her fold için doğruluk skoru hesapla
# Dönen değer: 5 elemanlı numpy dizisi (her fold için 1 skor)

xgb_cv = cross_val_score(xgb_model, X, y, cv=5, scoring='accuracy')

print(f'🔴 AdaBoost  CV Scores: {ada_cv.round(4)}')
print(f'   Ortalama: {ada_cv.mean():.4f} ± {ada_cv.std():.4f}')
# std küçükse → model farklı veri bölmelerinde tutarlı davranıyor (iyi!)
print()
print(f'🟢 XGBoost   CV Scores: {xgb_cv.round(4)}')
print(f'   Ortalama: {xgb_cv.mean():.4f} ± {xgb_cv.std():.4f}')

# ─── CV görselleştir ────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 5))
folds = [f'Fold {i+1}' for i in range(5)]
x = np.arange(5)

ax.plot(x, ada_cv, 'r-o', markersize=8, linewidth=2,
        label=f'AdaBoost (ort={ada_cv.mean():.4f})')
ax.plot(x, xgb_cv, 'g-s', markersize=8, linewidth=2,
        label=f'XGBoost (ort={xgb_cv.mean():.4f})')

# Shaded band: ortalama ± 1 std aralığını gölgeli bant olarak göster
# Bu bant dar ise model tutarlı, geniş ise değişken demektir.
ax.fill_between(x,
                ada_cv.mean() - ada_cv.std(),
                ada_cv.mean() + ada_cv.std(),
                alpha=0.1, color='red')
ax.fill_between(x,
                xgb_cv.mean() - xgb_cv.std(),
                xgb_cv.mean() + xgb_cv.std(),
                alpha=0.1, color='green')

ax.set_xticks(x)
ax.set_xticklabels(folds)
ax.set_ylabel('Accuracy', fontsize=12)
ax.set_title('5-Fold Cross Validation Karşılaştırması', fontsize=14, fontweight='bold')
ax.legend(fontsize=12)
ax.set_ylim(0.75, 0.90)
plt.tight_layout()
plt.show()

# ─── Farklı veri boyutlarında eğitim süresi analizi ─────────────────────────
# Veri büyüdükçe AdaBoost mu, XGBoost mu daha hızlı?

sizes = [50, 100, 200, 300, 400, 455]   # Kullanılacak örnek sayıları
ada_times_list = []
xgb_times_list = []

for s in sizes:
    # Eğitim verisinin ilk s örneğini al
    Xs = X_train.iloc[:s]
    ys = y_train.iloc[:s]

    # AdaBoost süresi
    m1 = AdaBoostClassifier(
        estimator=DecisionTreeClassifier(max_depth=1),
        n_estimators=100, learning_rate=0.1, algorithm='SAMME', random_state=42
    )
    t1 = time.time()
    m1.fit(Xs, ys)
    ada_times_list.append(time.time() - t1)

    # XGBoost süresi
    m2 = xgb.XGBClassifier(
        n_estimators=100, max_depth=3, learning_rate=0.1,
        eval_metric='logloss', random_state=42, verbosity=0
    )
    t2 = time.time()
    m2.fit(Xs, ys)
    xgb_times_list.append(time.time() - t2)

plt.figure(figsize=(10, 5))
plt.plot(sizes, ada_times_list, 'r-o', markersize=8, linewidth=2, label='AdaBoost')
plt.plot(sizes, xgb_times_list, 'g-s', markersize=8, linewidth=2, label='XGBoost')
# Beklenti: XGBoost büyük veride paralel işlem sayesinde daha hızlı olabilir.

plt.xlabel('Eğitim Örnek Sayısı', fontsize=12)
plt.ylabel('Eğitim Süresi (sn)', fontsize=12)
plt.title('Eğitim Süresi Karşılaştırması', fontsize=14, fontweight='bold')
plt.legend(fontsize=12)
plt.tight_layout()
plt.show()

print(f'\nFull dataset eğitim süreleri:')
print(f'  🔴 AdaBoost : {ada_time:.4f} sn')
print(f'  🟢 XGBoost  : {xgb_time:.4f} sn')

# ─── Tüm metrikleri tek tabloda özetle ──────────────────────────────────────
results_df = pd.DataFrame({
    'Metrik': ['Accuracy', 'AUC-ROC', 'F1 Score', 'Precision', 'Recall',
               'CV Ortalama', 'CV Std', 'Eğitim Süresi (sn)'],
    'AdaBoost 🔴': [
        f'{ada_acc:.4f}', f'{ada_auc:.4f}', f'{ada_f1:.4f}',
        f'{ada_prec:.4f}', f'{ada_recall:.4f}',
        f'{ada_cv.mean():.4f}', f'{ada_cv.std():.4f}',
        f'{ada_time:.4f}'
    ],
    'XGBoost 🟢': [
        f'{xgb_acc:.4f}', f'{xgb_auc:.4f}', f'{xgb_f1:.4f}',
        f'{xgb_prec:.4f}', f'{xgb_recall:.4f}',
        f'{xgb_cv.mean():.4f}', f'{xgb_cv.std():.4f}',
        f'{xgb_time:.4f}'
    ],
    'Kazanan': [
        # Her metrik için iki modeli karşılaştır ve kazananı belirle
        '🟢 XGBoost' if xgb_acc    >= ada_acc    else '🔴 AdaBoost',
        '🟢 XGBoost' if xgb_auc    >= ada_auc    else '🔴 AdaBoost',
        '🟢 XGBoost' if xgb_f1     >= ada_f1     else '🔴 AdaBoost',
        '🟢 XGBoost' if xgb_prec   >= ada_prec   else '🔴 AdaBoost',
        '🟢 XGBoost' if xgb_recall >= ada_recall else '🔴 AdaBoost',
        '🟢 XGBoost' if xgb_cv.mean() >= ada_cv.mean() else '🔴 AdaBoost',
        '🟢 XGBoost' if xgb_cv.std()  <= ada_cv.std()  else '🔴 AdaBoost',
        # Süre için: daha kısa süre kazanır
        '🟢 XGBoost' if xgb_time <= ada_time else '🔴 AdaBoost'
    ]
})

print('\n' + '='*65)
print('         📊 ADABOOST vs XGBOOST — SONUÇ TABLOSU')
print('='*65)
print(results_df.to_string(index=False))
print('='*65)

# Kazanılan kategori sayısını say
xgb_wins = sum(1 for k in results_df['Kazanan'] if 'XGBoost' in k)
ada_wins = sum(1 for k in results_df['Kazanan'] if 'AdaBoost' in k)
print(f'\n🏆 GENEL SONUÇ:')
print(f'   🟢 XGBoost kazandı  : {xgb_wins}/{len(results_df)} kategoride')
print(f'   🔴 AdaBoost kazandı : {ada_wins}/{len(results_df)} kategoride')