# -*- coding: utf-8 -*-
"""auto_mpg_eda_multi_reg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J493LuPtZLbsuBo1facGHuk9mx-Qe4UO
"""

# 📈 Polinom Regresyon (Polynomial Regression)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from matplotlib.patches import FancyArrowPatch

from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.metrics import r2_score, mean_squared_error

import warnings
warnings.filterwarnings('ignore')

# ── Grafik stili ayarları ──────────────────────────────────────────────────
plt.rcParams['figure.figsize'] = (13, 5)
plt.rcParams['figure.dpi'] = 110
plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.right'] = False
sns.set_style('whitegrid')
sns.set_palette('husl')

# ── Numpy yazdırma hassasiyeti ─────────────────────────────────────────────
np.set_printoptions(precision=4, suppress=True)

print('✅ Tüm kütüphaneler başarıyla yüklendi.')
print(f'   NumPy  : {np.__version__}')
print(f'   Pandas : {pd.__version__}')

import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the specific file in the dataset
file_path = "auto-mpg.csv"

# Load the dataset directly into a pandas DataFrame
df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "uciml/autompg-dataset",
    file_path
)

print("First 5 records:")
print(df.head())

# ── Temel bilgiler ────────────────────────────────────────────────────────
print('=' * 60)
print('📊 ARAÇ PERFORMANS VERİSİ (Auto MPG)')
print('=' * 60)
print(f'  Satır sayısı  : {df.shape[0]:,}')
print(f'  Sütun sayısı  : {df.shape[1]}')
print(f'  Model yılı aralığı: {df["model year"].min()} → {df["model year"].max()}')
print(f'  Benzersiz marka/model sayısı: {df["car name"].nunique()}')
print()

# ── İlk 5 satır ───────────────────────────────────────────────────────────
print('İlk 5 satır:')
# 'car name' ve 'mpg' gibi önemli sütunları gösterelim
print(df[['car name', 'mpg', 'horsepower', 'weight', 'model year']].head())

# ── Eksik değer analizi (Auto MPG için) ───────────────────────────────────
null_counts = df.isnull().sum()
null_pct    = (null_counts / len(df) * 100).round(2)

null_df = pd.DataFrame({
    'Eksik Sayı': null_counts,
    'Eksik Yüzde (%)': null_pct,
    'Veri Tipi': df.dtypes
}).sort_values('Eksik Sayı', ascending=False)

# Sadece eksik değer içeren sütunları göster
print('📋 Eksik Değer Raporu:')
# Sadece eksik olanlar varsa göster, yoksa "Eksik veri yok" mesajı ver
if null_counts.sum() > 0:
    print(null_df[null_df['Eksik Sayı'] > 0].to_string())
    print()
    print(f'⚠️ Toplam {(null_counts > 0).sum()} sütunda eksik veri mevcut.')
else:
    print("✅ Hiç eksik değer bulunamadı.")

# 1. Sütunların güncel listesini tekrar kontrol edelim
print("Mevcut sütunlar:", df.columns.tolist())

# 2. Eğer 'horsepower' listedeyse, 'df' içinde tekrar atama yapalım:
# Bazen sütun isminde gizli bir boşluk olabilir, onu temizleyelim:
df.columns = df.columns.str.strip()

# 1. Önce horsepower sütununu sayısal yap ve eksikleri temizle
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')
df = df.dropna(subset=['horsepower'])

# 2. Şimdi listeyi ve stats tablosunu yeniden oluştur
cols_to_analyze = ['mpg', 'horsepower', 'weight', 'acceleration']
stats = df[cols_to_analyze].describe().round(2)

# 3. Artık stats tablosunda 'horsepower' olduğu için aşağıdaki kod hata vermeyecek
print('📈 İstatistiksel Özet:')
print(stats)
print()
print('💡 İçgörüler:')
print(f'  • Ortalama Yakıt Tüketimi (MPG) : {stats.loc["mean", "mpg"]:.1f} MPG')
print(f'  • Ortalama Beygir Gücü (HP)    : {stats.loc["mean", "horsepower"]:.1f} HP')
print(f'  • Medyan (50%) Beygir Gücü     : {stats.loc["50%", "horsepower"]:.0f} HP')
print(f'  • En düşük Beygir Gücü         : {stats.loc["min", "horsepower"]:.0f} HP')
print(f'  • En yüksek Beygir Gücü        : {stats.loc["max", "horsepower"]:.0f} HP')
print(f'  • Standart Sapma (MPG)         : {stats.loc["std", "mpg"]:.2f} MPG')

# ── 1. Sütun seçimi ve temizleme ─────────────────────────────────────────
# mpg, horsepower, weight ve acceleration üzerinde çalışalım
cols = ['mpg', 'horsepower', 'weight', 'acceleration']
data = df[cols].copy()

# Zaten temizledik ama yine de tip dönüşümlerini garantileyelim
for col in cols:
    data[col] = pd.to_numeric(data[col], errors='coerce')

n_before = len(data)
data = data.dropna() # Eksik değerleri temizle
n_after  = len(data)

print(f'🧹 Temizleme Raporu:')
print(f'  Önceki satır sayısı : {n_before:,}')
print(f'  Sonraki satır sayısı: {n_after:,}')
print(f'  Silinen satır sayısı: {n_before - n_after:,} ({(n_before-n_after)/n_before*100:.2f}%)')
print()

# ── 2. IQR ile aykırı değer analizi ──────────────────────────────────────────
print('🔍 IQR Aykırı Değer Analizi:')
for col in cols:
    Q1  = data[col].quantile(0.25)
    Q3  = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = data[(data[col] < lower) | (data[col] > upper)]
    print(f'  {col:12s} | IQR={IQR:7.2f} | [{lower:7.2f}, {upper:7.2f}] | {len(outliers):,} aykırı değer ({(len(outliers)/len(data)*100):.2f}%)')

print()
print('✅ Veri temizleme ve aykırı değer analizi tamamlandı.')
print("İlk 5 satır:")
print(data.head())

## 5. 📊 Keşifsel Veri Analizi (EDA)

# ── Auto MPG Verisi için Dağılım Grafikleri ─────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(16, 4))
fig.suptitle('Araç Performans Değişkenlerinin Dağılımı', fontsize=14, fontweight='bold', y=1.05)

# Görselleştirmek istediğimiz sütunlar ve renkler
vars_info = [
    ('mpg',          '#e74c3c', 'Yakıt Tüketimi (MPG)'),
    ('horsepower',   '#3498db', 'Beygir Gücü (HP)'),
    ('weight',       '#2ecc71', 'Ağırlık (Weight)'),
]

for ax, (col, color, label) in zip(axes, vars_info):
    # Histogram + KDE (Kernel Density Estimate)
    sns.histplot(data[col], bins=30, kde=True, color=color, alpha=0.6, ax=ax)

    # Ortalama ve medyan çizgileri
    mean_val   = data[col].mean()
    median_val = data[col].median()
    ax.axvline(mean_val,  color='black',  linestyle='--', linewidth=1.5, label=f'Ort: {mean_val:.1f}')
    ax.axvline(median_val, color='orange', linestyle=':',  linewidth=1.5, label=f'Med: {median_val:.1f}')

    ax.set_title(label, fontweight='bold')
    ax.set_xlabel(label)
    ax.set_ylabel('Frekans')
    ax.legend(fontsize=9)

plt.tight_layout()
plt.show()

print('💡 Yorum:')
print('  • MPG değişkeni hafif sağa çarpık (skewed) olabilir.Positive Skewed')
print('  • Beygir gücü (horsepower) dağılımında daha yüksek değerlerde birikme var.Positive Skewed')
print('  • Normal dağılımdan sapmalar, modelin bazı aralıklarda daha fazla hata yapabileceğini gösterir. Positive Skewed')

# ── Korelasyon ısı haritası (Auto MPG) ───────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Veriyi seçelim
target_cols = ['mpg', 'horsepower', 'weight', 'acceleration']
corr_matrix = df[target_cols].corr()

# Sol: Korelasyon matrisi
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(
    corr_matrix, mask=mask, annot=True, fmt='.2f',
    cmap='coolwarm', center=0, vmin=-1, vmax=1,
    square=True, linewidths=1, ax=axes[0],
    annot_kws={'size': 12, 'weight': 'bold'}
)
axes[0].set_title('Korelasyon Matrisi', fontweight='bold', pad=12)

# Sağ: Scatter plot (İlişkiyi görselleştirme)
axes[1].scatter(df['horsepower'], df['mpg'], alpha=0.3, s=20,
                color='#e74c3c', label=f'HP–MPG (r={corr_matrix.loc["horsepower","mpg"]:.2f})')
axes[1].scatter(df['weight'], df['mpg'], alpha=0.3, s=20,
                color='#3498db', label=f'Weight–MPG (r={corr_matrix.loc["weight","mpg"]:.2f})')
axes[1].set_xlabel('Bağımsız Değişken (HP / Weight)')
axes[1].set_ylabel('Yakıt Tüketimi (MPG)')
axes[1].set_title('Scatter Plot — MPG ile Karşılaştırma', fontweight='bold')
axes[1].legend(fontsize=9, markerscale=1.5)

plt.tight_layout()
plt.show()

# 💡 Yorumlar
r_hp = corr_matrix.loc['horsepower','mpg']
r_weight = corr_matrix.loc['weight','mpg']
print('💡 Yorum:')
print(f'  • HP–MPG korelasyonu   : r = {r_hp:.2f} (Güçlü negatif ilişki)')
print(f'  • Weight–MPG korelasyonu: r = {r_weight:.2f} (Çok güçlü negatif ilişki)')
print(f'  • Negatif korelasyon: Araç ağırlaştıkça veya motor güçlendikçe MPG düşüyor.')
print(f'  • Polinom terimleri, doğrusal olmayan bu düşüşleri yakalamak için kritik!')

### 5.3 Box Plot — Aykırı Değer Görselleştirmesi

# ── Auto MPG için Box Plot ve Dağılım Analizi ──────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Sol: Değişkenlerin Box Plot ile karşılaştırılması (Ölçekleri farklı olduğu için ayrı ayrı düşünmek gerekebilir)
# Burada mpg ve horsepower değerlerini görselleştirelim
sns.boxplot(data=df[['mpg', 'acceleration']], palette=['#e74c3c', '#3498db'],
            width=0.5, fliersize=4, ax=axes[0])
axes[0].set_title('MPG ve İvmelenme Dağılımı (Box Plot)', fontweight='bold')

# Sağ: Horsepower dağılımı ve ortalaması
sns.histplot(df['horsepower'], bins=30, kde=True, color='#9b59b6', alpha=0.7, ax=axes[1])
axes[1].axvline(df['horsepower'].mean(), color='black', linestyle='--', linewidth=2,
                label=f'Ortalama HP: {df["horsepower"].mean():.1f}')
axes[1].set_xlabel('Beygir Gücü (HP)')
axes[1].set_ylabel('Frekans')
axes[1].set_title('Beygir Gücü Dağılımı', fontweight='bold')
axes[1].legend()

plt.tight_layout()
plt.show()

## 6. 🤖 Polinom Regresyon Modeli

# ── Özellik (X) ve Hedef (y) Değişkeni Belirleme ──────────────────────────
# Bağımsız değişken (X): 'horsepower' (veya 'weight')
# Bağımlı değişken (y) : 'mpg'

X = df[['horsepower']].values  # 2D olması şart (n_samples, 1)
y = df['mpg'].values           # 1D dizi (n_samples,)

# ── Train-Test Split ─────────────────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42
)

print('📊 Veri Bölme Sonuçları:')
print(f'  Toplam veri : {len(X):,} örnek')
print(f'  Eğitim seti : {len(X_train):,} örnek ({len(X_train)/len(X)*100:.0f}%)')
print(f'  Test seti   : {len(X_test):,} örnek  ({len(X_test)/len(X)*100:.0f}%)')
print()
print(f'  X_train boyutu: {X_train.shape}')
print(f'  y_train boyutu: {y_train.shape}')

### 6.2 Pipeline: PolynomialFeatures + LinearRegression

# ── Polinom dönüşümünü somut olarak görelim ───────────────────────────────
print('🔍 PolynomialFeatures Dönüşümü — Somut Örnek:')
print('   Girdi X = [[2], [3], [5]]')
print()

X_example = np.array([[2], [3], [5]])
for degree in [1, 2, 3]:
    pf = PolynomialFeatures(degree=degree, include_bias=True)
    X_transformed = pf.fit_transform(X_example)
    print(f'  Derece {degree}: {X_transformed.tolist()}')
    print(f'    Özellik isimleri: {pf.get_feature_names_out(["x"])}')
    print()

print('💡 "include_bias=True" → Sabit terim (1.0) sütunu eklenir.')
print('   Bu, LinearRegression intercept e karşılık gelir.')

# ── Model eğitimi döngüsü (Ölçeklendirme eklenmiş hali) ──────────────────────
degrees = [1, 2, 3, 4, 5, 7, 10]
models  = {}
results = []

for degree in degrees:
    # Pipeline'a StandardScaler ekledik!
    model = make_pipeline(
        PolynomialFeatures(degree=degree, include_bias=True),
        StandardScaler(),
        LinearRegression()
    )

    model.fit(X_train, y_train)
    models[degree] = model

    # Tahminler
    y_train_pred = model.predict(X_train)
    y_test_pred  = model.predict(X_test)

    # Metrikler
    train_r2   = r2_score(y_train, y_train_pred)
    test_r2    = r2_score(y_test,  y_test_pred)
    train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
    test_rmse  = np.sqrt(mean_squared_error(y_test,  y_test_pred))

    results.append({
        'Derece'    : degree,
        'Train R²'  : round(train_r2, 4),
        'Test R²'   : round(test_r2, 4),
        'Δ R²'      : round(train_r2 - test_r2, 4),
        'Train RMSE': round(train_rmse, 4),
        'Test RMSE' : round(test_rmse, 4),
    })

    flag = '⚠️ Overfitting!' if (train_r2 - test_r2) > 0.05 else '✅'
    print(f'Derece {degree:2d} | Train R²={train_r2:.4f} | Test R²={test_r2:.4f} | ΔR²={train_r2-test_r2:.4f} {flag}')

results_df = pd.DataFrame(results)
print('\n📋 Tam Sonuç Tablosu:')
print(results_df.to_string(index=False))

##Regresyon Eğrilerinin Görselleştirilmesi

# ── Regresyon Eğrileri (Auto MPG: Horsepower -> MPG) ────────────────────────
fig, axes = plt.subplots(2, 4, figsize=(18, 9))
axes = axes.flatten()

# Düzgün grafik çizimi için X ekseni aralığı
X_line = np.linspace(X.min(), X.max(), 400).reshape(-1, 1)

# Renk paleti
palette = sns.color_palette('husl', len(degrees))

# Her derece için ayrı subplot
for i, degree in enumerate(degrees):
    ax = axes[i]
    model = models[degree] # Önceki döngüde eğittiğiniz modeller
    row = results_df[results_df['Derece'] == degree].iloc[0]

    # Test verisini scatter olarak çiz
    ax.scatter(X_test, y_test, alpha=0.3, s=10, color='#95a5a6', label='Test Verisi')

    # Regresyon eğrisi
    ax.plot(X_line, model.predict(X_line), color=palette[i], linewidth=2.5, label=f'Derece {degree}')

    ax.set_title(f'Derece {degree} | Test R²={row["Test R²"]:.4f}', fontsize=10, fontweight='bold')
    ax.set_xlabel('Horsepower', fontsize=8)
    ax.set_ylabel('MPG', fontsize=8)
    ax.legend(fontsize=7, markerscale=3)

# Boş kalan subplotları gizle
if len(degrees) < len(axes):
    for j in range(len(degrees), len(axes)):
        axes[j].set_visible(False)

fig.suptitle('Polinom Derecesi Karşılaştırması: Horsepower → MPG İlişkisi', fontsize=15, fontweight='bold', y=1.03)
plt.tight_layout()
plt.show()

## 7. 📉 Model Performans Karşılaştırması

# ── Performans görselleştirmesi (Auto MPG) ──────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('Model Performans Karşılaştırması: Polinom Dereceleri', fontsize=14, fontweight='bold')

x_ticks = results_df['Derece'].tolist()

# ── 1. R² karşılaştırması ──────────────────────────────────────────────────
axes[0].plot(results_df['Derece'], results_df['Train R²'], 'o-', color='#2ecc71', linewidth=2.5, markersize=7, label='Train R²')
axes[0].plot(results_df['Derece'], results_df['Test R²'], 's--', color='#e74c3c', linewidth=2.5, markersize=7, label='Test R²')
axes[0].fill_between(results_df['Derece'], results_df['Train R²'], results_df['Test R²'], alpha=0.15, color='orange', label='Overfitting Boşluğu')
axes[0].set_xlabel('Polinom Derecesi', fontweight='bold')
axes[0].set_ylabel('R² Skoru')
axes[0].set_title('R² — Train vs Test')
axes[0].legend()
axes[0].set_xticks(x_ticks)

# ── 2. RMSE karşılaştırması ────────────────────────────────────────────────
axes[1].plot(results_df['Derece'], results_df['Train RMSE'], 'o-', color='#2ecc71', linewidth=2.5, markersize=7, label='Train RMSE')
axes[1].plot(results_df['Derece'], results_df['Test RMSE'], 's--', color='#e74c3c', linewidth=2.5, markersize=7, label='Test RMSE')
axes[1].set_xlabel('Polinom Derecesi', fontweight='bold')
axes[1].set_ylabel('RMSE (MPG)')
axes[1].set_title('RMSE — Train vs Test')
axes[1].legend()
axes[1].set_xticks(x_ticks)

# ── 3. ΔR² (Overfitting göstergesi) ───────────────────────────────────────
colors_bar = ['#27ae60' if v < 0.05 else '#e74c3c' for v in results_df['Δ R²']]
bars = axes[2].bar(results_df['Derece'], results_df['Δ R²'], color=colors_bar, alpha=0.8)
axes[2].axhline(y=0.05, color='orange', linestyle='--', linewidth=1.5, label='Eşik = 0.05')
axes[2].set_xlabel('Polinom Derecesi', fontweight='bold')
axes[2].set_ylabel('Train R² − Test R²')
axes[2].set_title('ΔR² — Overfitting Göstergesi')
axes[2].legend()
axes[2].set_xticks(x_ticks)

# Değer etiketleri
for bar, val in zip(bars, results_df['Δ R²']):
    axes[2].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001, f'{val:.4f}', ha='center', va='bottom', fontsize=8)

plt.tight_layout()
plt.show()

# En iyi model
best_row = results_df.loc[results_df['Test R²'].idxmax()]
print(f'🏆 En iyi model: Derece {int(best_row["Derece"])}')
print(f'   Test R²   = {best_row["Test R²"]:.4f}')
print(f'   Test RMSE = {best_row["Test RMSE"]:.4f} MPG')

### 7.1 K-Fold Cross-Validation ile Derece Seçimi

# ── K-Fold Cross-Validation ────────────────────────────────────────────────
print('🔄 5-Fold Cross-Validation Sonuçları:')
print('─' * 55)

kf = KFold(n_splits=5, shuffle=True, random_state=42)
cv_results = []

for degree in degrees:
    model = make_pipeline(
        PolynomialFeatures(degree=degree),
        LinearRegression()
    )
    # cross_val_score: her fold için R² skoru döndürür
    cv_scores = cross_val_score(model, X, y, cv=kf, scoring='r2')

    cv_results.append({
        'Derece'  : degree,
        'CV R² Ort': round(cv_scores.mean(), 4),
        'CV R² Std': round(cv_scores.std(),  4),
        'Min'     : round(cv_scores.min(),   4),
        'Max'     : round(cv_scores.max(),   4),
    })
    print(f'Derece {degree:2d} | CV R² = {cv_scores.mean():.4f} ± {cv_scores.std():.4f} | [{cv_scores.min():.4f}, {cv_scores.max():.4f}]')

cv_df = pd.DataFrame(cv_results)

print()
print('─' * 55)
best_cv_degree = cv_df.loc[cv_df['CV R² Ort'].idxmax(), 'Derece']
print('🏆 Cross-Validation a göre en iyi derece:{int(best_cv_degree)}')
print()
print('💡 Std ne kadar küçükse model o kadar KARARLIYDIR (stable).')
print(' Yüksek std → model bazı fold lara çok iyi, bazılarına kötü uyuyor.')

# ── Seçilen Modelin Performans Analizi (Auto MPG) ──────────────────────────
best_degree = int(results_df.loc[results_df['Test R²'].idxmax(), 'Derece'])
best_model  = models[best_degree]

y_test_pred  = best_model.predict(X_test)
y_train_pred = best_model.predict(X_train)
residuals    = y_test - y_test_pred

print(f'🏆 Seçilen Model: {best_degree}. Derece Polinom')
print(f'   Test R²   = {r2_score(y_test, y_test_pred):.5f}')
print(f'   Test RMSE = {np.sqrt(mean_squared_error(y_test, y_test_pred)):.4f} MPG')

# ── 4 panel analiz grafiği ────────────────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle(f'{best_degree}. Derece Polinom Regresyon — Kapsamlı Analiz (Horsepower → MPG)',
             fontsize=14, fontweight='bold', y=1.02)

# Panel 1: Regresyon eğrisi
axes[0,0].scatter(X_test, y_test, alpha=0.3, s=15, color='#7f8c8d', label='Test verisi')
axes[0,0].plot(X_line, best_model.predict(X_line), color='#e74c3c', linewidth=2.5, label=f'Derece {best_degree} Eğrisi')
axes[0,0].set_xlabel('Horsepower', fontweight='bold')
axes[0,0].set_ylabel('MPG', fontweight='bold')
axes[0,0].set_title('Regresyon Eğrisi')
axes[0,0].legend()

# Panel 2: Gerçek vs Tahmin
axes[0,1].scatter(y_test, y_test_pred, alpha=0.3, s=15, color='#2980b9')
lims = [min(y_test.min(), y_test_pred.min()), max(y_test.max(), y_test_pred.max())]
axes[0,1].plot(lims, lims, 'r--', linewidth=2, label='Mükemmel Tahmin')
axes[0,1].set_xlabel('Gerçek MPG', fontweight='bold')
axes[0,1].set_ylabel('Tahmin Edilen MPG', fontweight='bold')
axes[0,1].set_title(f'Gerçek vs Tahmin (R² = {r2_score(y_test, y_test_pred):.3f})')
axes[0,1].legend()

# Panel 3: Artık (Residual) dağılımı
sns.histplot(residuals, bins=30, kde=True, color='#8e44ad', alpha=0.7, ax=axes[1,0])
axes[1,0].axvline(0, color='red', linestyle='--', linewidth=2)
axes[1,0].set_xlabel('Artık (Gerçek - Tahmin) (MPG)', fontweight='bold')
axes[1,0].set_ylabel('Frekans')
axes[1,0].set_title('Artık (Residual) Dağılımı')

# Panel 4: Artık vs Tahmin (Homoscedasticity)
axes[1,1].scatter(y_test_pred, residuals, alpha=0.3, s=15, color='#27ae60')
axes[1,1].axhline(0, color='red', linestyle='--', linewidth=2)
axes[1,1].set_xlabel('Tahmin Edilen MPG', fontweight='bold')
axes[1,1].set_ylabel('Artık (MPG)', fontweight='bold')
axes[1,1].set_title('Artık vs Tahmin (Homoscedasticity)')

plt.tight_layout()
plt.show()

print('\n💡 Artık Analizi İçgörüleri:')
print(f'  • Ortalama artık ≈ {residuals.mean():.4f} MPG (0\'a yakın olması modelin tarafsız olduğunu gösterir)')
print(f'  • Artık std = {residuals.std():.4f} MPG')
print(f'  • Artık vs Tahmin grafiğinde örüntü yoksa modeliniz başarılıdır.')

## 9. 🔎 Model Katsayılarının İncelenmesi

# ── Katsayı çıkarımı (Auto MPG) ───────────────────────────────────────────────
lr_step   = best_model.named_steps['linearregression']
pf_step   = best_model.named_steps['polynomialfeatures']

intercept = lr_step.intercept_
coeffs    = lr_step.coef_
# 'horsepower' sütun ismini dinamik olarak alalım
feat_names = pf_step.get_feature_names_out(['horsepower'])

print(f'📐 {best_degree}. Derece Polinom Katsayıları:')
print('─' * 50)
print(f'  β₀ (intercept): {intercept:.6f}')
print()

# coefficients dizisinin ilk elemanı '1' (bias) olduğu için genellikle 0'dır,
# onu atlayıp diğerlerini yazdıralım
for i, (name, coef) in enumerate(zip(feat_names, coeffs)):
    print(f'  β{i} ({name:15s}): {coef:+.6f}')

# ── Polinom denklemini yaz ─────────────────────────────────────────────────
print('\n📝 Model Denklemi (Tahmini):')
equation = f'  MPG = {intercept:.4f}'
for i, (name, coef) in enumerate(zip(feat_names, coeffs)):
    if i > 0: # İlk terim (bias) katsayısını zaten intercept olarak aldık
        equation += f' + ({coef:+.4f})·{name}'
print(equation)

# ── Katsayı büyüklükleri (bar chart) ──────────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 5))
colors_c = ['#27ae60' if v >= 0 else '#e74c3c' for v in coeffs]

ax.bar(feat_names, coeffs, color=colors_c, alpha=0.8, edgecolor='black', linewidth=0.5)
ax.axhline(0, color='black', linewidth=1)
ax.set_xticklabels(feat_names, rotation=45, ha='right', fontsize=9)
ax.set_ylabel('Katsayı Değeri (Standardized)')
ax.set_title(f'{best_degree}. Derece Model Katsayıları (Özellik Önem Düzeyi)', fontweight='bold')
plt.tight_layout()
plt.show()

##İkinci Senaryo: MaxTemp → MinTemp Tahmini

# ── Auto MPG: Weight → Horsepower Modeli ──────────────────────────────────
# Ağırlık arttıkça motor gücü de (genellikle) artar.
X2 = df[['weight']].values
y2 = df['horsepower'].values

X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.20, random_state=42)

degrees2 = [1, 2, 3, 5, 7]
models2  = {}
results2 = []

for degree in degrees2:
    model = make_pipeline(PolynomialFeatures(degree), StandardScaler(), LinearRegression())
    model.fit(X2_train, y2_train)
    models2[degree] = model

    y2_test_pred = model.predict(X2_test)
    y2_train_pred = model.predict(X2_train)

    results2.append({
        'Derece'    : degree,
        'Train R²'  : round(r2_score(y2_train, y2_train_pred), 4),
        'Test R²'   : round(r2_score(y2_test, y2_test_pred), 4),
        'Test RMSE' : round(np.sqrt(mean_squared_error(y2_test, y2_test_pred)), 4),
    })

results2_df = pd.DataFrame(results2)

# ── Görselleştirme ─────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(15, 5))
fig.suptitle('Auto MPG: Weight → Horsepower Polinom Regresyon', fontsize=14, fontweight='bold')

# Scatter + eğriler
axes[0].scatter(X2_test, y2_test, alpha=0.3, s=15, color='#95a5a6', label='Test Verisi')

pal2 = sns.color_palette('Set2', len(degrees2))
X2_line = np.linspace(X2.min(), X2.max(), 400).reshape(-1, 1)

for j, degree in enumerate(degrees2):
    y_line = models2[degree].predict(X2_line)
    axes[0].plot(X2_line, y_line, color=pal2[j], linewidth=2,
                 label=f'D={degree} R²={results2_df.iloc[j]["Test R²"]:.3f}')

axes[0].set_xlabel('Weight (Ağırlık)')
axes[0].set_ylabel('Horsepower (Beygir Gücü)')
axes[0].set_title('Regresyon Eğrileri')
axes[0].legend(fontsize=8)

# R² karşılaştırması
axes[1].plot(results2_df['Derece'], results2_df['Train R²'], 'o-', linewidth=2.5, color='#2ecc71', label='Train R²')
axes[1].plot(results2_df['Derece'], results2_df['Test R²'], 's--', linewidth=2.5, color='#e74c3c', label='Test R²')
axes[1].set_xlabel('Polinom Derecesi')
axes[1].set_ylabel('R²')
axes[1].set_title('Performans — Derece Karşılaştırması')
axes[1].legend()
axes[1].set_xticks(degrees2)

plt.tight_layout()
plt.show()

print('📋 Auto MPG (Weight → Horsepower) Sonuç Tablosu:')
print(results2_df.to_string(index=False))

# ── Tahmin Fonksiyonu (Auto MPG için) ─────────────────────────────────────
def mpg_tahmin(hp_listesi, model=best_model):
    """
    Verilen beygir gücü (horsepower) değerleri için MPG tahmini yapar.
    """
    if isinstance(hp_listesi, (int, float)):
        hp_listesi = [hp_listesi]

    X_new = np.array(hp_listesi).reshape(-1, 1)
    y_pred = model.predict(X_new)

    # Modelin başarısını ölçen RMSE değerini kullanarak güven aralığı oluşturalım
    # Not: best_row, önceki analizdeki en iyi modelin sonuçlarını tutuyor olmalı
    rmse = best_row['Test RMSE']

    df_result = pd.DataFrame({
        'Horsepower': hp_listesi,
        'Tahmini MPG': y_pred.round(2),
        'Alt Sınır (%95 CI)': (y_pred - 1.96 * rmse).round(2),
        'Üst Sınır (%95 CI)': (y_pred + 1.96 * rmse).round(2),
    })
    return df_result

# ── Test Denemeleri ──────────────────────────────────────────────────────
# Farklı beygir güçlerine sahip araçların tahmini tüketimi
test_hp = [60, 90, 120, 150, 180, 210]
tahminler = mpg_tahmin(test_hp)

print(f'🚗 {best_degree}. Derece Polinom Modeli ile Yakıt Tüketimi Tahminleri:')
print(tahminler.to_string(index=False))