# -*- coding: utf-8 -*-
"""decision_tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18e64jP0qhZMBJve0Fe6W7J1bl8K10Ly9
"""

# Gerekli kütüphaneleri içe aktar
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import kagglehub

# Download latest version
path = kagglehub.dataset_download("blastchar/telco-customer-churn")

import os

# İndirilen klasördeki dosya adını path ile birleştiriyoruz
csv_file_path = os.path.join(path, "WA_Fn-UseC_-Telco-Customer-Churn.csv")

# Veriyi pandas ile okuyalım
df = pd.read_csv(csv_file_path)

# Verinin ilk 5 satırına göz atalım
display(df.head())

# Veri setindeki sütunların tiplerini ve eksik veri durumunu görelim
df.info()

print(f"Veri seti boyutu: {df.shape}")
print(f"Sınıf dağılımı:\n{df['Churn'].value_counts()}")

# Özellikler (X) ve hedef (y) ayrımı
X = df.drop('Churn', axis=1)
y = df['Churn']

print(f"Özellik matrisi boyutu: {X.shape}")
print(f"Hedef vektörü boyutu: {y.shape}")

# Eğitim ve test setlerine ayır (%80 eğitim, %20 test)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].median())

# 2. X ve y'yi ayır (customerID'yi de burada X'in içinden siliyoruz)
X = df.drop(['Churn', 'customerID'], axis=1, errors='ignore')
y = df['Churn'].map({'Yes': 1, 'No': 0})

# 3. Kategorik verileri (metinleri) One-Hot Encoding ile 1/0'lara dönüştürüyoruz
# (TotalCharges artık sayı olduğu için bu işlemden etkilenmeyecek)
X = pd.get_dummies(X, drop_first=True)

# 4. SENİN KODUN: Eğitim ve test setlerine ayır (%80 eğitim, %20 test ve stratify)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

print(f"Eğitim seti: {X_train.shape}")
print(f"Test seti: {X_test.shape}")

# Decision Tree modelini oluştur ve eğit
model = DecisionTreeClassifier(
    criterion='gini',      # Bölünme kriteri: Gini impurity
    max_depth=4,           # Maksimum derinlik (overfitting'i önlemek için)
    min_samples_split=10,  # Bir düğümü bölmek için minimum örnek sayısı
    min_samples_leaf=5,    # Bir yaprak düğümdeki minimum örnek sayısı
    random_state=42        # Tekrarlanabilirlik
)

model.fit(X_train, y_train)
print("Model eğitildi.")

# Test seti üzerinde tahmin yap
y_pred = model.predict(X_test)

# Model başarımını değerlendir
accuracy = accuracy_score(y_test, y_pred)
print(f"Doğruluk (Accuracy): {accuracy:.4f}")
print()

# Detaylı sınıflandırma raporu
print("Sınıflandırma Raporu:")
print(classification_report(y_test, y_pred, target_names=['Kalıyor - No (0)', 'Ayrılıyor - Yes (1)']))

# Karışıklık matrisi (Confusion Matrix)
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Kalıyor - No (0)', 'Ayrılıyor - Yes (1)'],
            yticklabels=['Kalıyor - No (0)', 'Ayrılıyor - Yes (1)'])
plt.title('Confusion Matrix')
plt.xlabel('Tahmin Edilen')
plt.ylabel('Gerçek')
plt.tight_layout()
plt.show()

# Decision Tree ağacını görselleştir
plt.figure(figsize=(60, 12))
plot_tree(
    model,
    feature_names=X.columns,
    class_names=['Kalıyor - No (0)', 'Ayrılıyor - Yes (1)'],
    filled=True,
    rounded=True,
    fontsize=10
)
plt.title('Decision Tree Görselleştirmesi', fontsize=16)
plt.tight_layout()
plt.show()

# Metinsel olarak karar ağacını görüntüle
tree_rules = export_text(
    model,
    feature_names=list(X.columns),
    spacing=3
)
print(tree_rules)

# Özellik önem sıralaması (Feature Importance)
feature_importance = pd.DataFrame({
    'feature': X.columns,
    'importance': model.feature_importances_
}).sort_values('importance', ascending=False)

print("En Önemli 10 Özellik:")
print(feature_importance.head(10))

# Görselleştir
plt.figure(figsize=(10, 6))
sns.barplot(data=feature_importance.head(10),
            x='importance', y='feature',
            palette='viridis')
plt.title('Feature Importance (En Önemli 10 Özellik)')
plt.xlabel('Önem Skoru')
plt.ylabel('Özellik')
plt.tight_layout()
plt.show()

# Modelin overfitting kontrolü için eğitim ve test doğruluklarını karşılaştır
train_accuracy = model.score(X_train, y_train)
test_accuracy = model.score(X_test, y_test)

print(f"Eğitim Doğruluğu: {train_accuracy:.4f}")
print(f"Test Doğruluğu:   {test_accuracy:.4f}")

if train_accuracy - test_accuracy > 0.1:
    print("⚠️  Model overfitting yapıyor olabilir (eğitim-test farkı > %10).")
elif train_accuracy - test_accuracy > 0.05:
    print("⚠️  Hafif overfitting olabilir.")
else:
    print("✓  Model genellemesi iyi (overfitting yok).")

# Farklı max_depth değerleri ile model karşılaştırması
depths = range(1, 16)
train_scores = []
test_scores = []

for depth in depths:
    dt = DecisionTreeClassifier(
        max_depth=depth,
        criterion='gini',
        min_samples_split=10,
        min_samples_leaf=5,
        random_state=42
    )
    dt.fit(X_train, y_train)
    train_scores.append(dt.score(X_train, y_train))
    test_scores.append(dt.score(X_test, y_test))

# Görselleştir
plt.figure(figsize=(10, 6))
plt.plot(depths, train_scores, 'b-o', label='Eğitim Doğruluğu')
plt.plot(depths, test_scores, 'r-s', label='Test Doğruluğu')
plt.xlabel('Max Depth')
plt.ylabel('Doğruluk')
plt.title('Derinlik - Doğruluk İlişkisi')
plt.legend()
plt.grid(True, alpha=0.3)
plt.xticks(depths)
plt.tight_layout()
plt.show()