# -*- coding: utf-8 -*-
"""kesifci_analiz_fifa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zADs8YJfjbXR5TKck9RPIeMuTaCyVe-W
"""

import pandas as pd
import numpy as np

# görselleştirme kütüphaneleri
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.patches as mpatches

#istatistik kütüphaneleri
from scipy import stats
import warnings

# ayarlar
warnings.filterwarnings('ignore') # uyarı mesajlarını kapatır
pd.set_option('display.max_columns', 50)# büyük veri de gelecek columm sayısını sınırlar
pd.set_option('display.max_rows', None)# satırı sınırlar
pd.set_option('display.float_format', lambda x: '%.2f' % x)#ekranda virgülden sonra kaç basamak

#Grafik stili ayarları
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette('husl')
plt.rcParams['figure.figsize']= (12,8)
plt.rcParams['font.size']= 12

print('Tüm kütüphaneler başarıyla yüklendi')
print(f'Pandas version: {pd.__version__}')
print(f'Numpy version: {np.__version__}')

print(f'Seaborn version: {sns.__version__}')

df_new= pd.read_csv('/content/fifa_eda.csv')
print(' Fifa Verisi')
print('='*50)
print(f'Boyut : {df_new.shape[0]} satır, {df_new.shape[1]} sütun')
print('='*50)
print(f'Bellek kullanımı: {df_new.memory_usage(deep=True).sum()/1024:.2f} KB')

#ilk beş satır yaazdırma
df_new.head()# parantez içine değer vermezsen default beş satır yazdırır

df_new.head(3)

# son 5 satırı bastırıyor
df_new.tail()

df_new.tail(2)

#rastgele beş satır
df_new.sample(5)

print('Veri tipleri')
print('='*40)
dtype_df= pd.DataFrame({
    'sütun': df_new.columns,
    'veri tipi': df_new.dtypes.values,
    'null değeri':df_new.isnull().sum().values,
    'null oranı(%)': (df_new.isnull().sum().values/len(df_new)*100).round(2),
    'unıque': df_new.nunique().values
})

print(dtype_df.to_string(index=False))

df_new.info()

df_new.shape

#  Sayısal değişkenlerie ilgili temel istatistikler
df_new.describe().T

#kategorik  değişkenlerin temel istatistikleri
df_new.describe(include=['object','category']).T

# Değişkenler türlerini ayır
sayisal_sutunlar = df_new.select_dtypes(include=['int64', 'float64']).columns
kategorik_sutunlar = df_new.select_dtypes(include=['object', 'category']).columns

eksik =df_new.isnull().sum()
eksik_oranı=(eksik/len(df_new)*100).round(2)
eksik_df=pd.concat([eksik,eksik_oranı],axis=1)
eksik_df.columns=["eksik_sayı","eksik_oran"]
eksik_df.sort_values("eksik_oran",ascending=False)

# Eksik veri görselleştirmesi
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Bar chart
eksik_olan = df_new.isnull().sum()
eksik_olan = eksik_olan[eksik_olan > 0].sort_values(ascending=True)

colors = ['#e74c3c' if x > 30 else '#f39c12' if x > 10 else '#3498db'
          for x in (eksik_olan / len(df_new) * 100)]

axes[0].barh(eksik_olan.index, eksik_olan.values, color=colors)
axes[0].set_title('Eksik Veri Sayısı (Sütun Bazında)', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Eksik Değer Sayısı')
for i, (val, col) in enumerate(zip(eksik_olan.values, eksik_olan.index)):
    axes[0].text(val + 1, i, f'{val} ({val/len(df_new)*100:.1f}%)', va='center')

# Heatmap
sns.heatmap(df_new.isnull(),
            yticklabels=False,
            cbar=True,
            cmap='viridis',
            ax=axes[1])
axes[1].set_title('Eksik Veri Haritası', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Sütunlar')

plt.tight_layout()
plt.suptitle('Eksik Veri Analizi', fontsize=16, fontweight='bold', y=1.02)
plt.show()

# Eksik verilerin mediana göre doldurulması
df_temiz = df_new.copy()


value_medyan = df_temiz['Value'].median()
df_temiz['Value'].fillna(value_medyan, inplace=True)

df_temiz['Club'].fillna('Free Agent', inplace=True)

# Free Agent olanların sözleşme tarihine "No Contract" (Sözleşme Yok) yazıyoruz
df_temiz.loc[df_temiz['Club'] == 'Free Agent', 'Contract Valid Until'] = df_temiz['Contract Valid Until'].fillna('No Contract')

# Geriye kalan (kulübü olup tarihi eksik olan 48 kişi) için "Unknown" (Bilinmiyor) yazıyoruz
df_temiz['Contract Valid Until'].fillna('Unknown', inplace=True)

# Eksik verilerin moda göre doldurulması
df_temiz['Skill Moves'].fillna(df_temiz['Skill Moves'].mode()[0], inplace=True)
df_temiz['International Reputation'].fillna(df_temiz['International Reputation'].mode()[0], inplace=True)


print(df_temiz.isnull().sum())

# sayısal değişkenler

sayisal_kolonlar =['Age','Overall','Potential','Value','Wage','International Reputation','Skill Moves','Joined','Height','Weight','Release Clause']

fig, axes = plt.subplots(len(sayisal_kolonlar), 3 , figsize=(18, 6*len(sayisal_kolonlar)))

for i, kolon in enumerate(sayisal_kolonlar):
  veri = df_temiz[kolon].dropna()

  axes[i,0].hist(veri, bins=30, color="steelblue",edgecolor='white',alpha=0.8)
  axes[i,0].axvline(veri.mean(), color='tomato', linestyle='dashed', linewidth=2, label=f'Ortalama{veri.mean():.2f}')
  axes[i,0].axvline(veri.median(), color='green', linestyle='dashed', linewidth=2, label=f'Medyan{veri.median():.2f}')
  axes[i,0].set_title(f'{kolon}-  Histogram')
  axes[i,0].legend()
  axes[i,0].set_xlabel(kolon)
  axes[i,0].set_ylabel('Frekans')

      # Box plot
  axes[i, 1].boxplot(veri, vert=True, patch_artist=True,
                       boxprops=dict(facecolor='lightblue', color='navy'),
                       medianprops=dict(color='red', linewidth=2))
  axes[i, 1].set_title(f'{kolon} - Box Plot')
  axes[i, 1].set_ylabel(kolon)


  veri.plot.kde(ax=axes[i,2],color='darkorange',linewidth=2)
  axes[i,2].fill_between(axes[i,2].lines[0].get_xdata(),
                        axes[i,2].lines[0].get_ydata(),
                        color='tomato',alpha=0.2)
  axes[i,2].set_title(f'{kolon}-  Kümülatif yoğunluk grafiği')
  axes[i,2].set_xlabel(kolon)


plt.suptitle('Sayısal Değişkenler- Tek Değişkenli Analiz', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

kategorik_kolonlar = ['Nationality','Club','Preferred Foot','Position','Contract Valid Until']
fig,axes =  plt.subplots(len(kategorik_kolonlar),1,figsize=(16, 6*len(kategorik_kolonlar)))
axes=axes.flatten()

renkler = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#FFA94D', '#845EF7', '#F06595', '#DDA0DD', '#90EE90']
for i,kolon in enumerate(kategorik_kolonlar):
  degerler=df_temiz[kolon].value_counts()
  yuzde = (degerler/len(df_temiz)*100).round(2)


  bars = axes[i].bar(degerler.index.astype(str),degerler.values,
                     color = renkler[:len(degerler)],edgecolor='white',linewidth=2)

  axes[i].set_title(f'{kolon}-Frekans  Dağılımı',fontsize=13,fontweight='bold')
  axes[i].set_xlabel(kolon)
  axes[i].set_ylabel('Frekans')

  for bar ,pct in zip(bars,yuzde.values):
    axes[i].text(bar.get_x()+bar.get_width()/2,
                 bar.get_height()+1,
                 f'{pct}%',
                 ha='center',
                 va='bottom',
                 fontsize=10)
plt.suptitle('Kategorik Değişkenler- Tek Değişkenli Analiz', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

#sayısal vs Sayısal : Scatter Plot

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# 1. SCATTER PLOT: Yaş (Age) vs Maaş (Wage) - Tercih Edilen Ayağa Göre
# Sağ ve Sol ayaklı oyuncuları ayırıyoruz
right_foot = df_temiz[df_temiz['Preferred Foot'] == 'Right']
left_foot = df_temiz[df_temiz['Preferred Foot'] == 'Left']


axes[0].scatter(right_foot['Age'], right_foot['Wage'], color='blue', label='Right Foot')
axes[0].scatter(left_foot['Age'], left_foot['Wage'], color='orange', label='Left Foot')
axes[0].set_xlabel('Age (Yaş)')
axes[0].set_ylabel('Wage (Maaş)')
axes[0].set_title('Yaş vs Maaş')
axes[0].legend()

# 2.Uluslararası İtibar (Reputation) vs Maaş (Wage)
df_temiz.boxplot(column='Wage', by='International Reputation', ax=axes[1], patch_artist=True)
axes[1].set_xlabel('Uluslararası İtibar (1-5 Arası)')
axes[1].set_ylabel('Wage (Maaş)')
axes[1].set_title('Uluslararası İtibar vs Maaş')


fig.suptitle('Bivariate Analysis (Çift Değişkenli Analiz)', fontsize=16)

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(18, 8))


# Yüzdelik oranları hesaplıyoruz
ct = pd.crosstab(df_temiz['Preferred Foot'],df_temiz['Skill Moves'],values=df_temiz['Skill Moves'],aggfunc='count')
ct_pct = pd.crosstab(df_temiz['Preferred Foot'], df_temiz['Skill Moves'], normalize='index') * 100
ct_pct.plot(kind='bar', stacked=True, ax=axes[0], colormap='viridis')


axes[0].set_title('Tercih Edilen Ayak ve Yetenek Hareketleri Dağılımı (%)')
axes[0].set_xlabel('Tercih Edilen Ayak')
axes[0].set_ylabel('Yüzde (%)')
axes[0].legend(title='Yetenek (Yıldız)', bbox_to_anchor=(1.05, 1), loc='upper left')
# X eksenindeki "Left" ve "Right" yazılarını düz tutmak için
axes[0].set_xticklabels(axes[0].get_xticklabels(), rotation=0)


# Uluslararası İtibar ve Yetenek (Isı Haritası)
ct2 = pd.crosstab(df_temiz['International Reputation'], df_temiz['Skill Moves'])
sns.heatmap(ct2, annot=True, fmt='d', cmap='plasma', ax=axes[1])

# Türkçe başlık ve eksen isimlendirmeleri
axes[1].set_title('Uluslararası İtibar ve Yetenek Hareketleri')
axes[1].set_xlabel('Yetenek Hareketleri (Yıldız)')
axes[1].set_ylabel('Uluslararası İtibar (Yıldız)')


# Genel başlık ve düzenlemeler
plt.suptitle('Çift Değişkenli Analiz (Kategorik vs Kategorik)', fontsize=16)
plt.tight_layout()
plt.show()

# kategorik vs sayısal

fig, axes = plt.subplots(1, 2, figsize=(16, 6))


# Oyuncuların genel gücü (Overall) sağlaklarda ve sollaklarda nasıl dağılıyor?
sns.violinplot(data=df_temiz, x='Preferred Foot', y='Overall', ax=axes[0], palette='husl')
axes[0].set_title('Tercih Edilen Ayak ve Genel Güç Dağılımı')
axes[0].set_xlabel('Tercih Edilen Ayak')
axes[0].set_ylabel('Genel Güç (Overall)')


# Sağ ayaklılar mı yoksa sol ayaklılar mı genel olarak daha yaşlı? Aykırı değerler kimler?
sns.boxplot(data=df_temiz, x='Preferred Foot', y='Age', ax=axes[1], palette='husl')
axes[1].set_title('Tercih Edilen Ayak ve Yaş Dağılımı')
axes[1].set_xlabel('Tercih Edilen Ayak')
axes[1].set_ylabel('Yaş (Age)')

plt.suptitle('Çift Değişkenli Analiz (Kategorik vs Sayısal)', fontsize=16)
plt.tight_layout()
plt.show()