# -*- coding: utf-8 -*-
"""Tolunay_YILMAZ_python_baslangic.ipynb adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mky-lx-Na70MM39-R4HwQ7CQL8RxrsdF

# 🐍 Python Başlangıç Defteri
### Adım adım, sade sorularla Python öğrenin!
---

## 1️⃣ print() Fonksiyonu
"""

# Örnek
print("Merhaba!")
print(42)
print("Sonuç:", 10 + 5)

"""### ✏️ Soru 1: Ekrana kendi adınızı yazdırın."""

# Buraya yazın:
isim="Tolunay"
print("Merhaba "+isim)

"""### ✏️ Soru 2: `print()` kullanarak 3 farklı satırda şunları yazdırın:
- Adınız
- Yaşınız
- Şehriniz
"""

# Buraya yazın:
ad="Tolunay"
yas=15
sehir="istanbul"
def yazdir(ad, yas, sehir):
    print(f"{ad} {yas} {sehir}")

yazdir(ad,yas,sehir)

"""---
## 2️⃣ Değişkenler
"""

# Örnek
isim = "Ahmet"
yas = 20
print(isim)
print(yas)

"""### ✏️ Soru 3: `sehir` adında bir değişken oluşturun ve değerini yazdırın."""

# Buraya yazın:

sehir="Iğdır"
print(sehir)

"""### ✏️ Soru 4: `sayi1 = 8` ve `sayi2 = 3` değişkenlerini tanımlayın. Toplamlarını `toplam` değişkenine atayın ve yazdırın."""

# Buraya yazın:
sayi1 = 8
sayi2 = 3

def toplam(a, b):
    return a + b
print(toplam(sayi1, sayi2))

"""---
## 3️⃣ Veri Tipleri
"""

# Örnek
print(type("merhaba"))   # str
print(type(10))          # int
print(type(3.14))        # float
print(type(True))        # bool

"""### ✏️ Soru 5: Aşağıdaki 4 değişkenin tipini `type()` ile yazdırın."""

a = "python"
b = 100
c = 9.99
d = False

# Buraya yazın:
print(type(a))
print(type(b))
print(type(c))
print(type(d))

"""### ✏️ Soru 6: `"25"` metnini sayıya (`int`), `7` sayısını metne (`str`) çevirin ve yazdırın."""

# Buraya yazın:
metin = "25"
sayi = 7
print(int(metin))
print(str(sayi))

"""---
## 4️⃣ Aritmetik İşlemler
"""

# Örnek
print(10 + 3)   # 13
print(10 - 3)   # 7
print(10 * 3)   # 30
print(10 / 3)   # 3.333...
print(10 // 3)  # 3  (tam bölme)
print(10 % 3)   # 1  (kalan)
print(2 ** 4)   # 16 (üs)

"""### ✏️ Soru 7: `a = 15`, `b = 4` için toplama, çıkarma, çarpma ve bölme işlemlerini yapın."""

a = 15
b = 4

# Buraya yazın:

print(a+b)
print(a-b)
print(a/b)
print(a*b)

"""### ✏️ Soru 8: 17'yi 5'e böldüğünüzde kalan nedir? `%` operatörü ile bulun."""

# Buraya yazın:

"""---
## 5️⃣ String (Metin) İşlemleri
"""

# Örnek
metin = "merhaba"
print(metin.upper())       # MERHABA
print(metin.lower())       # merhaba
print(len(metin))          # 7
print(metin[0])            # m  (ilk harf)
print(metin[-1])           # a  (son harf)

"""### ✏️ Soru 9: `isim = "python"` değişkeni için:
- Büyük harfle yazdırın
- Kaç harf olduğunu yazdırın
- İlk harfini yazdırın
"""

isim = "python"
# Buraya yazın:
print(isim.upper())
print(len(isim))
print(isim[0])

"""### ✏️ Soru 10: İki metni birleştirin. `ad = "Ali"` ve `soyad = "Yılmaz"` → `"Ali Yılmaz"` yazdırın."""

ad = "Ali"
soyad = "Yılmaz"
# Buraya yazın:
print(ad+" "+soyad)

"""### ✏️ Soru 11: f-string kullanarak şu çıktıyı üretin: `"Merhaba, ben Ali. 25 yaşındayım."`"""

ad = "Ali"
yas = 25
# Buraya yazın:
print((f"Merhaba, ben {ad}. {yas} yaşındayım."))

"""---
## 6️⃣ Koşullar (if / else)
"""

# Örnek
sayi = 10
if sayi > 0:
    print("Pozitif")
else:
    print("Sıfır veya negatif")

"""### ✏️ Soru 12: `yas = 16` değişkeni için; 18'den büyükse `"Ehliyet alabilir"`, değilse `"Ehliyet alamaz"` yazdırın."""

yas = 14
# Buraya yazın:

if yas >= 18:
    print("Ehliyet alabilir")
else:
    print("Ehliyet alamaz")

"""### ✏️ Soru 13: `sayi = 7` değişkeni için; çift mi tek mi olduğunu yazdırın. (`%` operatörü kullanın)"""

sayi = 7
# Buraya yazın:

if(sayi%2==0):
  print("cift")
else:
  print("tek")

"""### ✏️ Soru 14: `puan = 65` için not harfini yazdırın:
- 90 ve üstü → `"A"`
- 75 ve üstü → `"B"`
- 60 ve üstü → `"C"`
- 60 altı → `"F"`
"""

puan = 65
# Buraya yazın:
if(puan>=90 and puan<=100):
   print("A")
elif(puan>=75 and puan<90):
  print("B")
elif(puan>=60 and puan<75):
  print("C")
elif(puan<60 and puan>=0):
  print("F")
else:
  print("Geçerli değer aralığında değer giriniz 0-100")

"""---
## 7️⃣ for Döngüsü
"""

# Örnek
for i in range(5):
    print(i)   # 0, 1, 2, 3, 4

for i in range(1, 6):
    print(i)   # 1, 2, 3, 4, 5

"""### ✏️ Soru 15: 1'den 10'a kadar olan sayıları yazdırın."""

# Buraya yazın:
def say(n):
    for i in range(n):
      print(i)
say(10)

"""### ✏️ Soru 16: 1'den 10'a kadar olan sayıların toplamını hesaplayın."""

# Buraya yazın:

def topla(n):
    toplam = 0
    for i in range(n):
      toplam+=i
    print(toplam)

topla(10)

"""### ✏️ Soru 17: Aşağıdaki listedeki her meyveyi ayrı satırda yazdırın."""

meyveler = ["elma", "armut", "muz", "çilek"]
# Buraya yazın:
def yazdir(meyve_liste):
    for meyve in meyve_liste:
      print(meyve)

yazdir(meyveler)

"""---
## 8️⃣ Listeler
"""

# Örnek
liste = [10, 20, 30, 40, 50]
print(liste[0])       # 10 (ilk eleman)
print(liste[-1])      # 50 (son eleman)
print(len(liste))     # 5
liste.append(60)      # sona ekle
print(liste)

"""### ✏️ Soru 18: Aşağıdaki listede:
- İlk elemanı yazdırın
- Son elemanı yazdırın
- Listenin uzunluğunu yazdırın
"""

renkler = ["kırmızı", "mavi", "yeşil", "sarı", "beyaz"]
# Buraya yazın:
def renk_sec_ilk_son(meyve_liste):
    print((f"İlk Renk: {meyve_liste[0]} Son Renk: {meyve_liste[-1]}  Renk Sayısı: {len(meyve_liste)}"))

renk_sec_ilk_son(renkler)

"""### ✏️ Soru 19: Listeye `"turuncu"` ekleyin, sonra `"mavi"` yi silin ve listeyi yazdırın."""

renkler = ["kırmızı", "mavi", "yeşil", "sarı"]
# Buraya yazın:
renkler.append("turuncu")
renkler.remove("mavi")
print(renkler)

"""### ✏️ Soru 20: Sayılar listesindeki en büyük, en küçük değeri ve toplamı yazdırın."""

sayilar = [5, 12, 3, 8, 19, 1, 7]
# İpucu: max(), min(), sum() fonksiyonlarını kullanın
# Buraya yazın:

print(max(sayilar))
print(min(sayilar))
print(sum(sayilar))

"""---
## 9️⃣ Fonksiyonlar
"""

# Örnek
def topla(a, b):
    return a + b

sonuc = topla(3, 5)
print(sonuc)  # 8

"""### ✏️ Soru 21: İki sayıyı çarpan `carp(a, b)` fonksiyonu yazın ve `carp(4, 6)` ile test edin."""

# Buraya yazın:
def carp(a, b):
    return a * b

print(carp(4,6))

"""### ✏️ Soru 22: Bir isim alıp `"Merhaba, [isim]!"` şeklinde yazdıran `selamla(isim)` fonksiyonu yazın."""

# Buraya yazın:
def selamla(isim="Tolunay"):
    print(f"Merhaba, {isim}")
selamla("Ahmet")

"""### ✏️ Soru 23: Bir sayının çift mi tek mi olduğunu döndüren `cift_mi(sayi)` fonksiyonu yazın. `True` veya `False` dönsün."""

# Buraya yazın:
def cift_mi(sayi):
    if(sayi%2==0):
      return True
    else:
      return False

print(cift_mi(4))   # True
print(cift_mi(7))   # False

"""---
## 🔟 Hepsini Birleştir!

### ✏️ Soru 24:
Bir alışveriş sepeti uygulaması yapın:
- `sepet = []` listesi oluşturun
- 3 ürün ekleyin (`.append()`)
- `for` döngüsü ile ürünleri numaralı yazdırın
- Kaç ürün olduğunu yazdırın
"""

# Buraya yazın:
sepet = []
sepet.append("Muz")
sepet.append("Usb Kablo")
sepet.append("Ekmek")
for i in sepet:
  print(f"{sepet.index(i)} {i}")
print(f"ürün sayısı {len(sepet)}")

"""### ✏️ Soru 25:
Bir listede verilen notların ortalamasını hesaplayan `ortalama(notlar)` fonksiyonu yazın.
- `sum()` ve `len()` kullanabilirsiniz
- `[70, 85, 90, 60, 75]` listesiyle test edin
"""

# Buraya yazın:
def ortalama(notlar):
    return sum(notlar)/len(notlar)

test_notlari = [70, 85, 90, 60, 75]
# print(ortalama(test_notlari))  # 76.0 olmalı

print(f"ortalama {ortalama(test_notlari)}")

"""---
## 📊 İlerleme Tablosu

| Konu | Sorular | Bitti mi? |
|------|---------|----------|
| print() | 1, 2 | ☐ |
| Değişkenler | 3, 4 | ☐ |
| Veri Tipleri | 5, 6 | ☐ |
| Aritmetik | 7, 8 | ☐ |
| String | 9, 10, 11 | ☐ |
| if / else | 12, 13, 14 | ☐ |
| for Döngüsü | 15, 16, 17 | ☐ |
| Listeler | 18, 19, 20 | ☐ |
| Fonksiyonlar | 21, 22, 23 | ☐ |
| Birleştirici | 24, 25 | ☐ |

> 💡 Hata almaktan korkmayın — hatalar öğrenmenin en iyi yoludur!
"""