# -*- coding: utf-8 -*-
"""student_analysis_eda_simple_multi_reg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHXDz7NtzzReU4dsADL_jCXLBQ3kZ2-F
"""

import kagglehub
from kagglehub import KaggleDatasetAdapter

# Dosya adını belirtiyoruz (Bu veri setindeki .csv dosyasının adı budur)
file_path = "StudentPerformanceFactors.csv"

# load_dataset yerine dataset_load kullanman uyarını da giderecektir
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "lainguyn123/student-performance-factors",
  file_path
)

print("First 5 records:")
print(df.head())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 12
sns.set_style('whitegrid')

import warnings
warnings.filterwarnings('ignore')

df.head()

# Sütun isimlerini ve veri tiplerini incele
df.info()

# İstatistiksel özet
df.describe().T

##2. Veri Temizliği

# 1. Temizlik: String sütunlardaki özel karakterleri ve boşlukları temizle
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].astype(str).str.replace('\xa0', '', regex=False).str.strip()
        # Eğer bir sütun aslında sayısal ama 'object' olarak kaldıysa sayıya çevir
        df[col] = pd.to_numeric(df[col], errors='ignore')

# 2. Eksik Verileri Doldurma:
# Regresyon analizi NaN değerleri sevmez. 'object' (kategorik) olanları moduyla dolduruyoruz.
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].fillna(df[col].mode()[0])

# 3. Sayısal sütunlardaki eksiklikler varsa onları da ortalama ile doldur
for col in df.select_dtypes(include=['number']).columns:
    df[col] = df[col].fillna(df[col].mean())

# 4. Kategorik değişkenleri modele uygun hale getirme (Dummy Variables)
# Bu işlem metin verilerini sayısal sütunlara dönüştürür
df = pd.get_dummies(df, drop_first=True)

df.head()

# Temizlenmiş verinin bilgisi
print('Veri boyutu:', df.shape)
print('Eksik değerler:')
print(df.isnull().sum())
print('Sütun türleri:')
print(df.dtypes)

## 3. Keşifçi Veri Analizi (EDA)

# Korelasyon matrisi
plt.figure(figsize=(12, 10))
numeric_df = df.select_dtypes(include=[np.number])
corr = numeric_df.corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', square=True)
plt.title('Korelasyon Matrisi')
plt.tight_layout()
plt.show()

# 1. Korelasyon matrisini hesapla (sadece sayısal sütunlar)
# Kategorik verileri sayısal hale getirdiğin için artık tüm sütunlar sayısaldır.
corr = df.corr()

# 2. Hedef değişken 'Exam_Score' ile korelasyonları al
target = 'Exam_Score'
corr_with_target = corr[target].sort_values(ascending=False)

# 3. Sonuçları yazdır
print('Exam_Score ile Korelasyonlar (En Yüksekten En Düşüğe):')
print(corr_with_target)

print('\nExam_Score ile en yüksek 5 pozitif korelasyon:')
print(corr_with_target[1:6])

# Atilan_Gol dağılımı
plt.subplot(1, 2, 1)
sns.histplot(df[target], bins=10, kde=True)
plt.title(f'{target} Dağılımı')

plt.subplot(1, 2, 2)
sns.boxplot(y=df[target])
plt.title(f'{target} Kutu Grafiği')
plt.tight_layout()
plt.show()

##Basit Doğrusal Regresyon (Simple Linear Regression)

# Basit regresyon için değişkenler (En güçlü korelasyona sahip Attendance kullanılıyor)
X_simple = df[['Attendance']].values
y = df['Exam_Score'].values

# Eğitim ve test setlerine ayır (%80 eğitim, %20 test)
X_train, X_test, y_train, y_test = train_test_split(
    X_simple, y, test_size=0.2, random_state=42
)

print(f'Eğitim seti boyutu: {X_train.shape[0]}')
print(f'Test seti boyutu: {X_test.shape[0]}')

# Modeli oluştur ve eğit
model_simple = LinearRegression()
model_simple.fit(X_train, y_train)

# Tahmin yap
y_pred_test = model_simple.predict(X_test)

# Model Denklemi
beta_0 = model_simple.intercept_
beta_1 = model_simple.coef_[0]

print(f'\nModel Denklemi:')
print(f'Exam_Score = {beta_0:.4f} + ({beta_1:.4f} × Attendance)')

# Modeli oluştur ve eğit
model_simple = LinearRegression()
model_simple.fit(X_train, y_train)

# Tahmin yap
y_pred_train = model_simple.predict(X_train)
y_pred_test = model_simple.predict(X_test)

# Model parametreleri
beta_0 = model_simple.intercept_
beta_1 = model_simple.coef_[0]

print(f'Kesim Noktası (β₀): {beta_0:.4f}')
print(f'Eğim (β₁): {beta_1:.4f}')
print(f'Model Denklemi:')
print(f'Exam_Score = {beta_0:.4f} + ({beta_1:.4f} × Attendance)')

# Tahmin vs gerçek değerler (Test seti)
results = pd.DataFrame({
    'Gerçek Skor': y_test,
    'Tahmin Edilen Skor': y_pred_test,
    'Hata (Fark)': y_test - y_pred_test
})

# İlk 10 satırı yazdırarak karşılaştırma yapalım
print('Test Seti Tahminleri (İlk 10 Öğrenci):')
print(results.head(10))

# Ortalama hatayı görelim (Modelin ne kadar yanılıyor?)
print(f'\nOrtalama Hata Miktarı: {results["Hata (Fark)"].abs().mean():.2f} puan')

# Model performans metrikleri
rmse_train = np.sqrt(mean_squared_error(y_train, y_pred_train))
rmse_test = np.sqrt(mean_squared_error(y_test, y_pred_test))
mae_train = mean_absolute_error(y_train, y_pred_train)
mae_test = mean_absolute_error(y_test, y_pred_test)
r2_train = r2_score(y_train, y_pred_train)
r2_test = r2_score(y_test, y_pred_test)

metrics = pd.DataFrame({
    'Metrik': ['RMSE', 'MAE', 'R²'],
    'Eğitim': [f'{rmse_train:.3f}', f'{mae_train:.3f}', f'{r2_train:.3f}'],
    'Test': [f'{rmse_test:.3f}', f'{mae_test:.3f}', f'{r2_test:.3f}']
})
print('Model Performansı:')
print(metrics.to_string(index=False))

# Görselleştirme: Regresyon doğrusu
plt.figure(figsize=(10, 6))

# Tüm veri noktaları
plt.scatter(X_simple, y, color='blue', alpha=0.4, label='Gerçek Veri', s=40)

# Regresyon doğrusu (x sıralı)
x_line = np.linspace(X_simple.min(), X_simple.max(), 100).reshape(-1, 1)
y_line = model_simple.predict(x_line)
plt.plot(x_line, y_line, color='red', linewidth=3, label=f'Regresyon: y = {beta_0:.2f} + {beta_1:.2f}x')

plt.xlabel('Devam Durumu (Attendance)')
plt.ylabel('Sınav Skoru (Exam Score)')
plt.title('Basit Doğrusal Regresyon: Attendance → Exam Score')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

# Artık (Residual) analizi
residuals = y_test - y_pred_test

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.scatter(y_pred_test, residuals, alpha=0.7, s=60)
plt.axhline(y=0, color='red', linestyle='--')
plt.xlabel('Tahmin Edilen Değer')
plt.ylabel('Artık (Residual)')
plt.title('Artık Grafiği (Heteroskedastisite Kontrolü)')
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
sns.histplot(residuals, bins=5, kde=True)
plt.xlabel('Artık')
plt.title('Artık Dağılımı (Normallik Kontrolü)')
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print(f'Artıkların ortalaması: {np.mean(residuals):.4f}')
print(f'Artıkların standart sapması: {np.std(residuals):.4f}')

## 5. Çoklu Doğrusal Regresyon (Multiple Linear Regression)

# Korelasyon tablonu referans alarak en etkili 7 değişkeni seçiyoruz
# (Eksik verisi olmayan veya regresyona en çok katkı sağlayanlar)
selected_features = [
    'Attendance',
    'Hours_Studied',
    'Previous_Scores',
    'Tutoring_Sessions',
    'Parental_Education_Level_Postgraduate',
    'Distance_from_Home_Near',
    'Peer_Influence_Positive'
]

# Veri setinde bu sütunların varlığını doğrula
available_features = [f for f in selected_features if f in df.columns]
print(f'Kullanılacak özellikler: {available_features}')

# Çoklu regresyon için veri hazırlığı
X_multi = df[available_features].values
y_multi = df['Exam_Score'].values

# Eğitim ve test setlerine ayır
X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(
    X_multi, y_multi, test_size=0.2, random_state=42
)

# Modeli eğit
model_multi = LinearRegression()
model_multi.fit(X_train_m, y_train_m)

# Katsayıları incele
print('\nÖzelliklerin Sınav Skoru Üzerindeki Etkisi (Katsayılar):')
for feat, coef in zip(available_features, model_multi.coef_):
    print(f'   {feat}: {coef:.4f}')

# Çoklu regresyon için veri hazırlığı
# 'available_features' listende önceki adımda seçtiğin 7 özellik var
X_multi = df[available_features].values
y_multi = df['Exam_Score'].values # Artık hedefimiz Exam_Score

# Eğitim ve test setlerine ayır
X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(
    X_multi, y_multi, test_size=0.2, random_state=42
)

print(f'Eğitim seti boyutu: {X_train_m.shape}')
print(f'Test seti boyutu: {X_test_m.shape}')

# Çoklu doğrusal regresyon modelini oluştur ve eğit
model_multi = LinearRegression()
model_multi.fit(X_train_m, y_train_m)

# Tahmin
y_pred_train_m = model_multi.predict(X_train_m)
y_pred_test_m = model_multi.predict(X_test_m)
# Model katsayıları
print('Kesim Noktası (Intercept):', model_multi.intercept_.round(4))
print('Katsayılar:')
for feat, coef in zip(available_features, model_multi.coef_):
    print(f'   {feat}: {coef:.4f}')

# Denklem oluşturma (Exam_Score hedefli)
print(f'\nModel Denklemi:')
eq = f'Exam_Score = {model_multi.intercept_:.2f}'
for feat, coef in zip(available_features, model_multi.coef_):
    eq += f' + ({coef:.2f} × {feat})'
print(eq)

# Model performansı
rmse_train_m = np.sqrt(mean_squared_error(y_train_m, y_pred_train_m))
rmse_test_m = np.sqrt(mean_squared_error(y_test_m, y_pred_test_m))
mae_train_m = mean_absolute_error(y_train_m, y_pred_train_m)
mae_test_m = mean_absolute_error(y_test_m, y_pred_test_m)
r2_train_m = r2_score(y_train_m, y_pred_train_m)
r2_test_m = r2_score(y_test_m, y_pred_test_m)

metrics_multi = pd.DataFrame({
    'Metrik': ['RMSE', 'MAE', 'R²'],
    'Eğitim': [f'{rmse_train_m:.3f}', f'{mae_train_m:.3f}', f'{r2_train_m:.3f}'],
    'Test': [f'{rmse_test_m:.3f}', f'{mae_test_m:.3f}', f'{r2_test_m:.3f}']
})
print('Çoklu Regresyon Model Performansı:')
print(metrics_multi.to_string(index=False))

# İki modeli karşılaştır (Test seti üzerinden)
comparison = pd.DataFrame({
    'Model': ['Basit Regresyon (xG)', 'Çoklu Regresyon'],
    'RMSE': [f'{rmse_test:.3f}', f'{rmse_test_m:.3f}'],
    'MAE': [f'{mae_test:.3f}', f'{mae_test_m:.3f}'],
    'R²': [f'{r2_test:.3f}', f'{r2_test_m:.3f}']
})
print('Model Karşılaştırması (Test Seti):')
print(comparison.to_string(index=False))

# Gerçek vs Tahmin karşılaştırması (Çoklu Regresyon)
plt.figure(figsize=(10, 6))

# Tahmin edilen vs Gerçek değerler
plt.scatter(y_test_m, y_pred_test_m, alpha=0.6, color='darkblue', s=60, label='Tahminler')

# Mükemmel tahmin doğrusu (y=x)
plt.plot([y_test_m.min(), y_test_m.max()], [y_test_m.min(), y_test_m.max()],
         'r--', linewidth=2, label='Mükemmel Tahmin (y=x)')

plt.xlabel('Gerçek Sınav Skoru')
plt.ylabel('Tahmin Edilen Sınav Skoru')
plt.title('Çoklu Regresyon: Gerçek vs Tahmin (Performans Analizi)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

# Özellik önem sırası (katsayıların mutlak değerine göre)
feature_importance = pd.DataFrame({
    'Özellik': available_features,
    'Katsayı': model_multi.coef_,
    '|Katsayı|': np.abs(model_multi.coef_)
}).sort_values('|Katsayı|', ascending=True)

# Grafiği daha şık hale getirmek için düzenleme
plt.figure(figsize=(10, 6))

# Renkleri ve sırayı belirle
feature_importance = feature_importance.sort_values('|Katsayı|', ascending=True)

# Çubukları çiz
bars = plt.barh(feature_importance['Özellik'], feature_importance['Katsayı'],
                color='forestgreen', alpha=0.7, edgecolor='white')

# Izgara çizgilerini arkaya al
plt.grid(axis='x', linestyle='--', alpha=0.6)

# Başlık ve etiketler
plt.title('Özelliklerin Sınav Skoru Üzerindeki Etkisi', fontsize=14, fontweight='bold')
plt.xlabel('Katsayı Değeri (Etki Büyüklüğü)', fontsize=12)

# Değerleri çubukların sağ tarafına düzgünce yazdır
for i, v in enumerate(feature_importance['Katsayı']):
    plt.text(v + 0.02, i, f'{v:.2f}', va='center', fontsize=11)

plt.tight_layout()
plt.show()

# Tüm modelleri özetle
print('=' * 60)
print('REGRESYON ANALİZİ ÖZETİ: EXAM_SCORE TAHMİN MODELİ')
print('=' * 60)

print(f'1. BASİT DOĞRUSAL REGRESYON')
print(f'   Hedef: Exam_Score')
print(f'   Özellik: Attendance')
print(f'   Denklem: Exam_Score = {beta_0:.2f} + {beta_1:.2f} × Attendance')
print(f'   Test R²: {r2_test:.3f}')
print(f'   Test RMSE: {rmse_test:.3f}')
print(f'   Test MAE: {rmse_test:.3f}')

print(f'\n2. ÇOKLU DOĞRUSAL REGRESYON')
print(f'   Hedef: Exam_Score')
print(f'   Özellikler: {", ".join(available_features)}')
print(f'   Test R²: {r2_test_m:.3f}')
print(f'   Test RMSE: {rmse_test_m:.3f}')
print(f'   Test MAE: {mae_test_m:.3f}')

print(f'\n3. MODEL KARŞILAŞTIRMASI')
better_model = 'Çoklu Regresyon' if r2_test_m > r2_test else 'Basit Regresyon'
print(f'   R² değerine göre daha iyi model: {better_model}')
print(f'   Performans Artışı (R² bazında): %{(r2_test_m - r2_test)*100:.2f}')
print('=' * 60)