# -*- coding: utf-8 -*-
"""Tolunay_YILMAZtemel_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15AbOSPO8_SSBJgV8T-lF-KEUV0QGeuK5

# 🐍 Temel Python Komutları - Alıştırma Defteri

Bu defterde Python'un temel konularını öğrenecek ve pratik sorularla kendinizi geliştireceksiniz.

---

## 1️⃣ Değişkenler ve Veri Tipleri
"""



"""### 🔸 Soru 1:
Aşağıdaki değişkenleri tanımlayın ve her birinin tipini `type()` fonksiyonu ile yazdırın:
- `sehir`: "Ankara" (string)
- `nüfus`: 5700000 (integer)
- `sicaklik`: 23.5 (float)
- `yagmur_yagıyor`: False (boolean)
"""

# Cevabınızı buraya yazın:
sehir= "Ankara"
nüfus=  5700000
sicaklik=  23.5
yagmur_yagıyor=  False
print(type(sehir))
print(type(nüfus))
print(type(sicaklik))
print(type(yagmur_yagıyor))

"""### 🔸 Soru 2:
Bir değişkeni `int`'ten `float`'a, `float`'tan `str`'e dönüştürün ve sonuçları yazdırın.

Örnek: `sayi = 42` → `float(sayi)` → `str(float(sayi))`
"""

# Cevabınızı buraya yazın:
sayi = 42
print(type(float(sayi)))
print(float(sayi))
print(type(str(float(sayi))))
print((sayi))

"""---
## 2️⃣ Operatörler
"""

# Örnek: Aritmetik operatörler
a = 10
b = 3
print(a*b)
print(a+b)
print(a-b)
print(a/b)
print(a%b)
print(a**b)

"""### 🔸 Soru 3:
Kullanıcıdan alınan iki sayı olduğunu varsayın: `x = 17`, `y = 5`
- Toplamlarını, farklarını ve çarpımlarını yazdırın.
- 17'nin 5'e bölümünden kalanı yazdırın.
- 2'nin 8. kuvvetini hesaplayın.
"""

# Cevabınızı buraya yazın:
x=17
y=5
print(x+y)
print(x-y)
print(x*y)
print(x%y)
print(2**8)

"""### 🔸 Soru 4:
Karşılaştırma operatörlerini kullanarak aşağıdaki ifadelerin sonuçlarını (True/False) yazdırın:
- 10 > 5
- 3 == 3.0
- "elma" != "armut"
- 7 <= 7
"""

# Cevabınızı buraya yazın:
print(10>5)
print(type(3)==type(3.0))
print("elma"!="armut")
print(7<=7)

"""---
## 3️⃣ String (Metin) İşlemleri
"""

# Örnek: String metodları
metin = "Merhaba Python!"

print(metin.upper())       # Büyük harf
print(metin.lower())       # Küçük harf
print(metin.replace("Python", "Dünya"))  # Değiştirme
print(len(metin))          # Uzunluk
print(metin[0:7])          # Dilimleme

"""### 🔸 Soru 5:
`cumle = "  python programlama dili çok güçlüdür  "` değişkeni için:
- Baştaki ve sondaki boşlukları temizleyin (`.strip()`)
- İlk harfini büyük yapın (`.capitalize()`)
- Kaç kelimeden oluştuğunu bulun (`.split()` ve `len()` kullanın)
- "güçlü" kelimesinin cümlede olup olmadığını kontrol edin (`in` operatörü)
"""

# Cevabınızı buraya yazın:
cumle = "  python programlama dili çok güçlüdür  "
print(cumle.strip())
dis_bosluksuz_cumle=cumle.strip()
print(dis_bosluksuz_cumle.capitalize())
kelime_liste=cumle.split()
print(len(bosluksuz_cumle))
print("güçlü " in cumle)

"""### 🔸 Soru 6 (f-string):
Ad, soyad ve yaş bilgilerini f-string kullanarak şu formatta yazdırın:

`"Merhaba, ben [AD] [SOYAD]. [YAŞ] yaşındayım."`
"""

# Cevabınızı buraya yazın:
ad = "Fatma"
soyad = "Yıldız"
yas = 28
print(f"Merhaba, ben {ad}, {soyad}. {yas} yaşındayım.")

"""---
## 4️⃣ Koşullu İfadeler (if / elif / else)
"""

# Örnek
puan = 75

if puan >= 90:
    print("AA")
elif puan >= 80:
    print("BA")
elif puan >= 70:
    print("BB")
elif puan >= 60:
    print("CB")
else:
    print("Başarısız")

"""### 🔸 Soru 7:
Bir sayının pozitif, negatif ya da sıfır olduğunu kontrol eden if-elif-else bloğu yazın.
"""

# Cevabınızı buraya yazın:
sayi = 0
if(sayi>0):
  print("pozitif")
elif(sayi<0):
 print("negatif")
else:
  print("sifir")

"""### 🔸 Soru 8:
Bir sayının 2'ye ve 3'e tam bölünüp bölünmediğini kontrol edin. 4 farklı durum vardır:
- Hem 2'ye hem 3'e bölünebilir
- Sadece 2'ye bölünebilir
- Sadece 3'e bölünebilir
- Hiçbirine bölünemiyor
"""

# Cevabınızı buraya yazın:
n = 0
if(n%2==0 & n%3==0):
   print("Hem 2'ye hem 3'e bölünebilir")
elif(n%2==0):
   print("2'ye bölünebilir")
elif(n%3==0):
   print("3'e bölünebilir")
else:
    print("Hiçbirine bölünemiyor")

"""---
## 5️⃣ Döngüler (for / while)
"""

# Örnek: for döngüsü
for i in range(1, 6):
    print(f"{i}. adım")

print("---")

# Örnek: while döngüsü
sayac = 0
while sayac < 3:
    print(f"Sayaç: {sayac}")
    sayac += 1

"""### 🔸 Soru 9:
`for` döngüsü ile 1'den 10'a kadar olan sayıların toplamını hesaplayın.
"""

# Cevabınızı buraya yazın:

toplam=0
for i in range(1, 11):
   toplam+=i

print(toplam)

"""### 🔸 Soru 10:
`while` döngüsü ile kullanıcının girdiği sayıya (n=5) kadar Fibonacci dizisini yazdırın.

Örnek çıktı: `0, 1, 1, 2, 3`
"""

# Cevabınızı buraya yazın:
n = 5
a=0
b=1
while(i<n)

"""### 🔸 Soru 11 (İç İçe Döngü):
5x5 çarpım tablosunu yazdırın. Her satır şu formatta olsun:

`1x1=1  1x2=2  1x3=3 ...`
"""

# Cevabınızı buraya yazın:

list =[1,2,3,4,5]
for i in list:
   for y in list:
      print(str(i)+"x"+str(y)+"="+str(i*y))

"""---
## 6️⃣ Listeler
"""

# Örnek
meyveler = ["elma", "armut", "çilek", "muz"]

print(meyveler[0])          # İlk eleman
print(meyveler[-1])         # Son eleman
print(meyveler[1:3])        # Dilimleme
meyveler.append("kivi")     # Ekleme
meyveler.remove("armut")    # Silme
print(meyveler)

"""### 🔸 Soru 12:
Aşağıdaki listede:
- En büyük ve en küçük elemanı bulun
- Listeyi sıralayın
- 7 sayısının listede kaç kez geçtiğini bulun
- Listeyi tersine çevirin
"""

# Cevabınızı buraya yazın:
sayilar = [3, 7, 1, 9, 7, 4, 7, 2, 8]
print(max(sayilar))
print(min(sayilar))
print(sayilar.index(7))
sayilar.reverse()
print(sayilar)

"""### 🔸 Soru 13 (List Comprehension):
List comprehension kullanarak:
- 1-20 arasındaki çift sayıların listesini oluşturun
- Bir kelime listesindeki 4'ten uzun kelimeleri filtreleyin
"""

# Cevabınızı buraya yazın:
kelimeler = ["at", "kaplan", "it", "fil", "kedi", "aslan", "köpek"]
list=[]
for i in range(1, 21):
  if(i%2==0):
    list.append(i)

print(list)


for kelime in kelimeler:
    if(len(kelime)<4):
        kelimeler.remove(kelime)

print(kelimeler)

"""---
## 7️⃣ Sözlükler (Dictionary)
"""

# Örnek
ogrenci = {
    "ad": "Ali",
    "soyad": "Kaya",
    "yas": 20,
    "notlar": [85, 90, 78]
}

print(ogrenci["ad"])
print(ogrenci.get("yas"))
ogrenci["bolum"] = "Bilgisayar Mühendisliği"
print(ogrenci.keys())
print(ogrenci.values())

"""### 🔸 Soru 14:
Bir kitap sözlüğü oluşturun (`baslik`, `yazar`, `yil`, `sayfa_sayisi`) ve:
- Tüm anahtar-değer çiftlerini döngüyle yazdırın
- `fiyat` anahtarı ekleyin
- `yazar` anahtarını silin
"""

# Cevabınızı buraya yazın:
kitap = {
    "baslik": "Kırmızı Başlıklı Kız",
    "yazar": "Veli",
    "yil": 2020,
    "sayfa_sayisi": 350,
    "fiyat":150

}
for i in kitap.values():
    print(i)
print(kitap.keys())
print(kitap.values())

"""---
## 8️⃣ Fonksiyonlar
"""

# Örnek
def selamla(isim, nezaket="Merhaba"):
    return f"{nezaket}, {isim}!"

print(selamla("Ayşe"))
print(selamla("Mehmet", "İyi günler"))

"""### 🔸 Soru 15:
Bir sayının asal olup olmadığını kontrol eden `asal_mi(n)` fonksiyonu yazın.
- 1'den 20'ye kadar olan asal sayıları bu fonksiyonu kullanarak yazdırın.
"""

# Cevabınızı buraya yazın:
def asal_mi(n):
   if(n==2):
    return n
   if(n==3):
     return n
   elif(n%2==0):
    return 0
   elif(n%3==0):
    return 0
   else:
      return n


        # buraya kodunuzu yazın
for i in range(1,20):
    print(asal_mi(i))

"""### 🔸 Soru 16:
Bir listenin ortalamasını, en büyük ve en küçük elemanını döndüren `liste_istatistik(liste)` fonksiyonu yazın.
Fonksiyon 3 değer döndürsün: `(ortalama, minimum, maksimum)`
"""

# Cevabınızı buraya yazın:
import statistics
def liste_istatistik(liste):
    print(f"Ortalama: {statistics.mean(liste)}, Min: {min(liste)}, Max: {max(liste)}")

test = [4, 8, 15, 16, 23, 42]
liste_istatistik(test)

"""---
## 9️⃣ Hata Yönetimi (try / except)
"""

# Örnek
try:
    sonuc = 10 / 0
except ZeroDivisionError:
    print("Sıfıra bölme hatası!")
except Exception as e:
    print(f"Beklenmeyen hata: {e}")
finally:
    print("İşlem tamamlandı.")

"""### 🔸 Soru 17:
Kullanıcıdan bir sayı alındığını varsayın (`girdi = "abc"`).
Bu değeri int'e çevirmeye çalışırken `ValueError` hatası oluşabilir.
try-except ile bunu yakalayan ve anlamlı bir mesaj veren kod yazın.
"""

# Cevabınızı buraya yazın:
girdi = "abc"


try:
    sayi = int(girdi)
    print("Girilen sayı:", sayi)

except ValueError:
    print("Hata: Sayıya çevrilemeyen bir değer girdiniz!")

except Exception as e:
    print(f"Beklenmeyen hata: {e}")

"""---
## 🔟 Bonus: Kapsamlı Uygulama

### 🔸 Soru 18 (Bütünleştirici):
Bir **not defteri uygulaması** yazın:
- `notlar` adında boş bir liste oluşturun
- `not_ekle(metin)` fonksiyonu: Notu listeye ekler
- `not_listele()` fonksiyonu: Tüm notları numaralandırarak yazdırır
- `not_sil(index)` fonksiyonu: Verilen indexteki notu siler, hatalı index için hata mesajı verir

Fonksiyonları test edin: 3 not ekleyin, listeleyin, ortadakini silin, tekrar listeleyin.
"""

# Cevabınızı buraya yazın:
notlar = []

def not_ekle(metin):
    notlar.append(metin)

def not_listele():
    for i in notlar:
        print(i)

def not_sil(index):
    notlar.pop(index)


not_ekle("Python öğren")
not_ekle("Alıştırmaları tamamla")

not_listele()

not_sil(1)

not_listele()

"""---
## 📊 Özet Çizelgesi

| Konu | Sorular | Tamamlandı mı? |
|------|---------|----------------|
| Değişkenler & Tipler | 1, 2 | ☐ |
| Operatörler | 3, 4 | ☐ |
| String İşlemleri | 5, 6 | ☐ |
| Koşullar | 7, 8 | ☐ |
| Döngüler | 9, 10, 11 | ☐ |
| Listeler | 12, 13 | ☐ |
| Sözlükler | 14 | ☐ |
| Fonksiyonlar | 15, 16 | ☐ |
| Hata Yönetimi | 17 | ☐ |
| Bütünleştirici | 18 | ☐ |

> 💡 **İpucu:** Takıldığınız yerde `help()` fonksiyonunu veya Python dokümantasyonunu kullanın!
"""