# -*- coding: utf-8 -*-
"""Unsupervised .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DlQOiMSI1SiVyDg6JH6f_cmJnREB5_Pq
"""

# Temel kütüphaneler
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

#veri ön işleme
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer


# Algoritmalar ( Kümeleme)
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from sklearn.mixture import GaussianMixture

#Boyut indirme
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

#Değerlendirme Metrikleri

from sklearn.metrics import silhouette_score
from sklearn.metrics import calinski_harabasz_score
from sklearn.metrics import davies_bouldin_score


from scipy.cluster.hierarchy import dendrogram, linkage


plt.rcParams['figure.figsize'] = [16, 10]
plt.rcParams['font.size'] = 14
sns.set_style('whitegrid')
print('Herşey hazır')

import kagglehub
import os
# Download latest version
path = kagglehub.dataset_download("rikdifos/credit-card-approval-prediction")

full_path = os.path.join(path, 'application_record.csv')
data = pd.read_csv(full_path)

# 4. RAM'i korumak için 440 bin satırın rastgele 30.000'ini alıyoruz
df = data.sample(n=5000, random_state=42).copy()

print("Veri başarıyla yüklendi!")
print("Yeni ve hafif veri boyutu:", df.shape)

#Istatıksel Ozet
df.describe().T

print('Eksik değerler')
print('--'*50)
print(df.isnull().sum()[df.isnull().sum()>0])
print(f'toplam eksik değer: {df.isnull().sum().sum()}')
print('--'*50)

df_columns =df.columns.str.strip()

# 1. ID sütununu silmek yerine indeks (satır numarası) yapıyoruz
df.set_index('ID', inplace=True)

# 2. Eksik verilerimiz metin olduğu için ortalama yerine sabit bir kelime atıyoruz
imputer = SimpleImputer(strategy='constant', fill_value='Unknown')

# 3. Imputer'ı veriye uygulayıp bozulan tablo yapısını tekrar DataFrame'e çeviriyoruz
df_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns, index=df.index)

# 4. Eksik veri kalıp kalmadığını kontrol ediyoruz
print('Eksik değerler')
print('--'*50)
print(df_imputed.isnull().sum()[df_imputed.isnull().sum() > 0])
print(f'Toplam eksik değer: {df_imputed.isnull().sum().sum()}')

# 1. YENİ ADIM: Metinsel verileri sayılara (0 ve 1'lere) dönüştürme (One-Hot Encoding)
# Bu işlem 'F' veya 'M' gibi metinleri makinenin anlayacağı formata sokar.
df_encoded = pd.get_dummies(df_imputed, drop_first=True)

# 2. ADIM: Ölçeklendirme (Standartlaştırma)
scaler = StandardScaler()
# DİKKAT: df_imputed yerine artık sayılara dönüştürülmüş df_encoded'ı veriyoruz
x_scaled_array = scaler.fit_transform(df_encoded)

# 3. ADIM: İşlem sonucunda bozulan tablo yapısını tekrar DataFrame'e çevirme
x_scaled = pd.DataFrame(x_scaled_array, columns=df_encoded.columns, index=df_encoded.index)

print('Ölçeklenmiş veri seti')
print('--'*50)
display(x_scaled.head(2))

import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score # Fonksiyon tekil

# 1. Listeleri tanımla
inertia = []
silhouette_scores = [] # Liste çoğul
K_range = range(2, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    # Değişken adının X_scaled (büyük X) olduğundan emin ol
    labels = kmeans.fit_predict(x_scaled)

    inertia.append(kmeans.inertia_)
    # Liste ismine (çoğul), fonksiyonun (tekil) sonucunu ekle
    silhouette_scores.append(silhouette_score(x_scaled, labels))

# Görselleştirme
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Sol Grafik: Elbow Method
axes[0].plot(K_range, inertia, 'bx-', linewidth=2)
axes[0].set_xlabel('K (Küme Sayısı)')
axes[0].set_ylabel('Inertia (WCSS)')
axes[0].set_title('The Elbow Method')
axes[0].grid(True, alpha=0.3)

# Sağ Grafik: Silhouette Score
# Hata Buradaydı: 'silhouette_score' (fonksiyon) yerine 'silhouette_scores' (liste) olmalı
axes[1].plot(K_range, silhouette_scores, 'rx-', linewidth=2)
axes[1].set_xlabel('K (Küme Sayısı)')
axes[1].set_ylabel('Silhouette Score')
axes[1].set_title('Silhouette Analysis')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# En iyi K değerini hesapla
optimal_k = K_range[np.argmax(silhouette_scores)]
print(f'En iyi silhouette skoru: {max(silhouette_scores):.4f}')
print(f'Optimum küme sayısı: {optimal_k}')

# Optimum  K ile  K-Means modelini egit
optimal_k = 4
kmeans = KMeans(n_clusters=optimal_k, init='k-means++', random_state=42,n_init=10)
kmeans_labels=kmeans.fit_predict(x_scaled)

print('K-means Kümeleme Sonuçları:')
print(f'Kume sayısı: {optimal_k}')
print(f'Silhoutte Skoru: {silhouette_score(x_scaled, kmeans_labels):.4f}')
print(f'Davies Bouldin Skoru: {davies_bouldin_score(x_scaled, kmeans_labels):.4f}')
print(f'Calinski Harabasz Skoru: {calinski_harabasz_score(x_scaled, kmeans_labels):.4f}')
print(f'\n Kume dagilimi:')
print(pd.Series(kmeans_labels).value_counts().sort_index())

# 1. En iyi küme sayısıyla (örneğin 3 veya 4) nihai modeli kuruyoruz
# Yukarıdaki adımdan gelen optimal_k değerini kullanıyoruz
kmeans_nihai = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
kume_etiketleri = kmeans_nihai.fit_predict(x_scaled)

# 2. Bu kümeleri orijinal (veya imputed) tabomuza yeni bir sütun olarak ekliyoruz
df_imputed['Musteri_Segmenti'] = kume_etiketleri

# 1. Eksik olan 'AGE' ve 'YEARS_EMPLOYED' sütunlarını gün verilerinden oluşturuyoruz
df_imputed['AGE'] = np.abs(df_imputed['DAYS_BIRTH']) / 365.25
df_imputed['YEARS_EMPLOYED'] = np.abs(df_imputed['DAYS_EMPLOYED'].replace(365243, 0)) / 365.25

# 2. Şimdi bu sütunları içeren özet listemizi tekrar tanımlayalım
ozet_sutunlar = ['AMT_INCOME_TOTAL', 'CNT_CHILDREN', 'AGE', 'YEARS_EMPLOYED', 'CNT_FAM_MEMBERS']

# 3. Ve gruplayıp ortalamasını alalım
print("Müşteri Segmentlerinin Profilleri (Hocanın Tablosunun Senin Verine Uyarlanmış Hali):")
print('--'*40)
display(df_imputed.groupby('Musteri_Segmenti')[ozet_sutunlar].mean().round(2))

# PCA ile K-Means gorsellestirmesi
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(x_scaled)

plt.figure(figsize=(12, 8))
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=kmeans_labels, cmap='viridis',
                      alpha=0.7, s=50, edgecolors='k', linewidth=0.5)
plt.colorbar(scatter, label='Kume')
plt.title('K-Means Kumeleme Sonuclari (PCA ile 2 Boyutlu Gosterim)', fontsize=14, fontweight='bold')
plt.xlabel(f'PC1 (%{pca.explained_variance_ratio_[0]*100:.1f} varyans)', fontsize=12)
plt.ylabel(f'PC2 (%{pca.explained_variance_ratio_[1]*100:.1f} varyans)', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()

pca = PCA(n_components=2) # Veriyi 2 ana bileşene indiriyoruz
x_pca = pca.fit_transform(x_scaled)

plt.figure(figsize=(12,8))
# Buraya x_scaled yerine x_pca[:200] yazıyoruz
linked = linkage(x_pca[:200], method='ward')
dendrogram(linked, truncate_mode='level', p=5)
# Çizgiyi de daha düşük bir yere (örneğin y=20) çekebilirsin çünkü PCA sonrası mesafeler küçülür
plt.axhline(y=20, color='r', linestyle='--')
plt.show()

# Agglomerative
agg_clustering  =AgglomerativeClustering(n_clusters=optimal_k,linkage='ward')
agg_labels=agg_clustering.fit_predict(x_scaled)

print('Hiyerarşik (Agglomerative)Kümeleme Sonuçları:')
print(f'Kümeleme Sayısı: {optimal_k}')
print(f'Bağlantı Yöntemi :ward')
print(f'Silhoutte Skoru: {silhouette_score(x_scaled, agg_labels):.4f}')
print(f'Davies Bouldin Skoru: {davies_bouldin_score(x_scaled, agg_labels):.4f}')
print(f'Calinski Harabasz Skoru: {calinski_harabasz_score(x_scaled, agg_labels):.4f}')
print(f'\n Kume dagilimi:')
print(pd.Series(agg_labels).value_counts().sort_index())

# Hiyerarsik kumelerin gorsellestirmesi
plt.figure(figsize=(12, 8))
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=agg_labels, cmap='plasma',
                      alpha=0.7, s=50, edgecolors='k', linewidth=0.5)
plt.colorbar(scatter, label='Kume')
plt.title('Hiyerarsik Kumeleme Sonuclari (PCA ile 2 Boyutlu Gosterim)', fontsize=14, fontweight='bold')
plt.xlabel(f'PC1 (%{pca.explained_variance_ratio_[0]*100:.1f} varyans)', fontsize=12)
plt.ylabel(f'PC2 (%{pca.explained_variance_ratio_[1]*100:.1f} varyans)', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()

#dbscan
from sklearn.neighbors import NearestNeighbors

neighbors = NearestNeighbors(n_neighbors=5)
neighbors_fit = neighbors.fit(x_scaled)
distances, indices = neighbors_fit.kneighbors(x_scaled)
distances = np.sort(distances[:, 4], axis=0)

plt.figure(figsize=(12, 5))
plt.plot(distances, 'b-', linewidth=2)
plt.title('k-Mesafe Grafigi (k=5) - eps Degeri Belirleme', fontsize=14, fontweight='bold')
plt.xlabel('Veri Noktalari (siralanmis)', fontsize=12)
plt.ylabel('5. En yakin komsu mesafesi', fontsize=12)
plt.axhline(y=2.5, color='r', linestyle='--', alpha=0.7, label='eps = 2.5')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

dbscan= DBSCAN(eps=2.5,min_samples=5)
dbscan_labels=dbscan.fit_predict(x_scaled)

n_clusters_db = len(set(dbscan_labels)) - (1 if -1 in dbscan_labels else 0)
n_noise =list(dbscan_labels).count(-1)

print('DBSCAN Kümeleme Sonuçları:')
print(f'Kümeleme Sayısı: {n_clusters_db}')
print(f'Gürültü Sayısı: {n_noise}')
print(f'Gürültü oranı: {n_noise/len(dbscan_labels):.4f}')

if n_clusters_db >1:
  print(f'Silhoutte Skoru: {silhouette_score(x_scaled, dbscan_labels):.4f}')
  print(f'Davies Bouldin Skoru: {davies_bouldin_score(x_scaled, dbscan_labels):.4f}')
  print(f'Calinski Harabasz Skoru: {calinski_harabasz_score(x_scaled, dbscan_labels):.4f}')
print(f'\n Kume dagilimi:')
print(pd.Series(dbscan_labels).value_counts().sort_index())

from sklearn.decomposition import PCA
from sklearn.mixture import GaussianMixture
import matplotlib.pyplot as plt

# 1. ÖNCE PCA (Veriyi 2 boyuta indiriyoruz - Bu adım çok hızlıdır)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(x_scaled)

# 2. SONRA GMM (Modeli ağır olan x_scaled yerine, hafif olan X_pca üzerinde eğitiyoruz)
# covariance_type='diag' kullanarak hesaplamayı daha da hızlandırıyoruz
gmm = GaussianMixture(n_components=4, covariance_type='diag', random_state=42)
gmm_labels = gmm.fit_predict(X_pca) # İşte hız kazandıran değişiklik burada!

# 3. GÖRSELLEŞTİRME
plt.figure(figsize=(12, 8))
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=gmm_labels, cmap='viridis',
                      alpha=0.6, s=40, edgecolors='none')

plt.colorbar(scatter, label='GMM Kümeleri')
plt.title('Hızlandırılmış GMM Kümeleme (PCA Verisi Üzerinden)', fontsize=14)
plt.xlabel('Ana Bileşen 1')
plt.ylabel('Ana Bileşen 2')
plt.grid(True, alpha=0.2)
plt.show()

print("GMM Modeli saniyeler içinde başarıyla tamamlandı!")