# -*- coding: utf-8 -*-
"""vehicle_damage_detection_cnn_vs_vgg16_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0Sj5oeCBYmwQWzEkykA7vsMv7Qg7AdN
"""

# ── Kurulum ────────────────────────────────────────────────────
!pip install tensorflow numpy matplotlib scikit-learn opencv-python Pillow seaborn -q

# ── Kütüphane Açıklamaları ─────────────────────────────────────

import os
import random
import numpy as np              # Sayısal işlemler, dizi/matris operasyonları
import matplotlib.pyplot as plt # Görselleştirme (grafik, histogram, resim gösterimi)
import seaborn as sns           # İstatistiksel görselleştirme (confusion matrix ısı haritası)
import cv2                      # OpenCV — görüntü okuma, yeniden boyutlandırma, renk dönüşümü
from PIL import Image, ImageDraw  # Pillow — sentetik görüntü üretimi
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models, optimizers, callbacks
# layers   → Conv2D, Dense, Dropout vb. katman nesneleri
# models   → Sequential ve Functional API
# optimizers → Adam, SGD vb.
# callbacks → EarlyStopping, ReduceLROnPlateau vb.

from tensorflow.keras.preprocessing.image import ImageDataGenerator
# Görüntü artırma ve batch akışı için

from tensorflow.keras.applications import VGG16
# ImageNet üzerinde eğitilmiş hazır model (transfer learning)

from sklearn.model_selection import train_test_split
# Veri setini eğitim/doğrulama/test'e bölmek için

from sklearn.metrics import (
    classification_report,  # Precision, Recall, F1 raporu
    confusion_matrix,        # Tahmin hataları matrisi
    roc_auc_score,           # ROC eğrisi altındaki alan
    roc_curve                # ROC eğrisi noktaları
)

# ── Tekrarlanabilirlik ─────────────────────────────────────────
# Aynı sonuçları her çalıştırmada elde etmek için sabit tohum
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ── Donanım Kontrolü ───────────────────────────────────────────
gpus = tf.config.list_physical_devices('GPU')
print(f"TensorFlow : {tf.__version__}")
print(f"GPU Sayısı : {len(gpus)}")
print(f"Cihaz      : {'GPU ⚡' if gpus else 'CPU (GPU yoksa eğitim yavaş olabilir)'}")

## 3. Veri Hazırlama ve Ön İşleme

# ── Yeni Ayarlar (CPU Optimizasyonlu Araç Hasar Tespiti) ──
IMG_SIZE      = 64       # CPU'da hızlı çalışması için 128'den 64'e düşürdük
BATCH_SIZE    = 16       # İşlemciyi boğmamak için 32'den 16'ya çektik
EPOCHS        = 15       # Hızlı bir test için 15 epoch yeterli olacaktır
USE_REAL_DATA = False    # Önce sentetik veriyle sistemin hatasız çalıştığını göreceğiz
DATA_DIR      = './data' # İleride gerçek veri kullanırsak ana klasörümüz
CLASSES       = ['hasarsiz', 'hasarli'] # Yeni sınıflarımız

print("Yeni Ayarlar:")
print(f"  Görüntü boyutu : {IMG_SIZE}×{IMG_SIZE}")
print(f"  Batch büyüklüğü: {BATCH_SIZE}")
print(f"  Max epoch      : {EPOCHS}")
print(f"  Veri modu      : {'Gerçek Veri' if USE_REAL_DATA else 'Sentetik Araç Verisi'}")

# ── Sentetik Veri Üreteci ─────────────────────────────────────
# Gerçek veri yokken algoritmayı test etmek için kullanılır.
# Basit geometrik şekillerle hasarlı ve hasarsız araçlar temsil edilir.

def generate_synthetic_image(label: int, size: int = 64) -> np.ndarray:
    """
    label=0 → Hasarsız: Düzgün kaporta, temiz çizgiler
    label=1 → Hasarlı: Üzerinde göçük (koyu lekeler) ve çizikler (beyaz/siyah çizgiler) olan kaporta
    """
    # Açık gri/mavi asfalt benzeri arka plan
    img = Image.new('RGB', (size, size),
                    color=(random.randint(180, 200),
                           random.randint(180, 200),
                           random.randint(190, 210)))
    draw = ImageDraw.Draw(img)
    cx, cy = size // 2, size // 2   # Merkez koordinatı

    # Aracın temel rengi (rastgele)
    car_color = (random.randint(50, 200), random.randint(50, 200), random.randint(50, 200))
    w, h = size // 3, size // 6

    # ── Ortak Çizim (Araç İskeleti) ───────────────────────────
    # Alt Gövde
    draw.rectangle([cx-w, cy-h, cx+w, cy+h], fill=car_color)
    # Tavan / Camlar
    draw.polygon([(cx-w+10, cy-h), (cx-w+20, cy-h-15), (cx+w-20, cy-h-15), (cx+w-10, cy-h)], fill=(150, 200, 255))
    # Tekerlekler
    draw.ellipse([cx-w+5, cy+h-8, cx-w+20, cy+h+7], fill=(30, 30, 30))
    draw.ellipse([cx+w-20, cy+h-8, cx+w-5, cy+h+7], fill=(30, 30, 30))

    if label == 1:  # ── Hasarlı Araç ──────────────────────────
        # Göçük efekti (Düzensiz koyu renkli poligonlar)
        for _ in range(random.randint(1, 3)):
            dx = random.randint(cx-w+5, cx+w-15)
            dy = random.randint(cy-h+5, cy+h-5)
            draw.polygon([(dx, dy), (dx+8, dy-4), (dx+5, dy+6)], fill=(50, 50, 50))

        # Çizik efekti (Rastgele açılı ince çizgiler)
        for _ in range(random.randint(2, 5)):
            sx = random.randint(cx-w, cx+w-10)
            sy = random.randint(cy-h, cy+h)
            draw.line([(sx, sy), (sx+random.randint(5, 12), sy+random.randint(-10, 10))], fill=(255, 255, 255), width=1)

    # Gerçekçilik için rastgele Gaussian gürültü ekle
    arr = np.array(img, dtype=np.float32)
    arr += np.random.normal(0, 6, arr.shape)
    return np.clip(arr, 0, 255).astype(np.uint8)


def load_synthetic_data(n_per_class: int = 300):
    """Her sınıftan n_per_class adet görüntü üretir (CPU optimizasyonu için 300'e düşürüldü)."""
    X, y = [], []
    for label in [0, 1]:
        for _ in range(n_per_class):
            X.append(generate_synthetic_image(label, IMG_SIZE))
            y.append(label)
    # Karıştır (önce hepsi hasarsız, sonra hepsi hasarlı olmasın)
    combined = list(zip(X, y))
    random.shuffle(combined)
    X, y = zip(*combined)
    return np.array(X), np.array(y)


# ── Gerçek Veri Yükleyici ──────────────────────────────────────
def load_real_data(data_dir: str, img_size: int = 64):
    """
    Klasör yapısı beklenir:
        data/
          hasarsiz/   → *.jpg, *.jpeg, *.png
          hasarli/    → *.jpg, *.jpeg, *.png
    """
    X, y = [], []
    for label, cls in enumerate(CLASSES):
        folder = os.path.join(data_dir, cls)
        if not os.path.exists(folder):
            raise FileNotFoundError(
                f"Klasör bulunamadı: {folder}\n"
                f"Beklenen yapı: {data_dir}/hasarsiz/ ve {data_dir}/hasarli/"
            )
        files = [f for f in os.listdir(folder)
                 if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
        print(f"  {cls}: {len(files)} dosya bulundu")
        for fname in files:
            img = cv2.imread(os.path.join(folder, fname))
            if img is None:
                continue  # Bozuk dosyaları atla
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)   # Renk kanalı düzelt
            img = cv2.resize(img, (img_size, img_size))  # Boyutu standartlaştır
            X.append(img)
            y.append(label)
    return np.array(X), np.array(y)


# ── Veriyi Yükle ───────────────────────────────────────────────
print("Veri yükleniyor...")
if USE_REAL_DATA:
    X, y = load_real_data(DATA_DIR, IMG_SIZE)
else:
    X, y = load_synthetic_data(n_per_class=300)
    print("Sentetik araç verileri üretildi.")

print(f"\nToplam görüntü : {len(X)}")
print(f"Hasarsız (0)   : {np.sum(y==0)}")
print(f"Hasarlı (1)    : {np.sum(y==1)}")
print(f"Görüntü şekli  : {X.shape[1:]}  → (yükseklik × genişlik × kanal)")
print(f"Piksel aralığı : [{X.min()}, {X.max()}]  (henüz normalize edilmedi)")

# ── Örnek Görüntüleri Görselleştir ────────────────────────────
fig, axes = plt.subplots(2, 8, figsize=(18, 5))
fig.suptitle('Veri Seti Örnekleri — Sentetik Araç Görüntüleri',
             fontsize=13, fontweight='bold')

for row, label in enumerate([0, 1]):
    # Her sınıftan (Hasarsız ve Hasarlı) ilk 8 görüntüyü al
    idxs = np.where(y == label)[0][:8]
    for col, idx in enumerate(idxs):
        axes[row, col].imshow(X[idx])
        axes[row, col].set_title(CLASSES[label].upper(), fontsize=10,
                                 color='green' if label==0 else 'red')
        axes[row, col].axis('off')

plt.tight_layout()
plt.show()

# ── Piksel Değeri Dağılımını İncele (RGB) ─────────────────────
# Normalizasyon öncesi [0-255] aralığındaki ham renk dağılımları
fig, axes = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle('Araç Kaportası Piksel Değeri Dağılımı (RGB Kanalları)', fontsize=12)
renkler = ['red', 'green', 'blue']
kanal_isimleri = ['Kırmızı (R)', 'Yeşil (G)', 'Mavi (B)']

for i, (ax, renk, isim) in enumerate(zip(axes, renkler, kanal_isimleri)):
    ax.hist(X[:50, :, :, i].flatten(), bins=50, color=renk, alpha=0.7, edgecolor='white')
    ax.set_title(isim)
    ax.set_xlabel('Piksel Değeri [0-255]')
    ax.set_ylabel('Frekans')
    ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# ── Normalizasyon ──────────────────────────────────────────────
# float32: float64'e göre 2× daha az bellek tüketir, hesaplamayı hızlandırır
X_norm = X.astype(np.float32) / 255.0

print("Normalizasyon öncesi:")
print(f"  dtype  : {X.dtype}")
print(f"  min    : {X.min()}")
print(f"  max    : {X.max()}")
print(f"  mean   : {X.mean():.2f}")

print("\nNormalizasyon sonrası:")
print(f"  dtype  : {X_norm.dtype}")
print(f"  min    : {X_norm.min():.4f}")
print(f"  max    : {X_norm.max():.4f}")
print(f"  mean   : {X_norm.mean():.4f}")

# ── Eğitim / Doğrulama / Test Bölünmesi ──────────────────────
# stratify=y → Her kümedeki hasarsız/hasarlı oranı korunur
# Örn: Verimizde %50 hasarsız, %50 hasarlı var; train, val ve test'te de oran aynı kalacak

X_train, X_temp, y_train, y_temp = train_test_split(
    X_norm, y,
    test_size    = 0.30,   # %70 eğitim, %30 geri kalan
    random_state = SEED,
    stratify     = y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size    = 0.50,   # Geri kalanın %50'si val, %50'si test (yani tüm verinin %15-%15'i)
    random_state = SEED,
    stratify     = y_temp
)

print("\nVeri Bölünmesi:")
print(f"  Eğitim    : {len(X_train):5d} görüntü  "
      f"(Hasarsız:{np.sum(y_train==0)}, Hasarlı:{np.sum(y_train==1)})")
print(f"  Doğrulama : {len(X_val):5d} görüntü  "
      f"(Hasarsız:{np.sum(y_val==0)}, Hasarlı:{np.sum(y_val==1)})")
print(f"  Test      : {len(X_test):5d} görüntü  "
      f"(Hasarsız:{np.sum(y_test==0)}, Hasarlı:{np.sum(y_test==1)})")

## 5. Data Augmentation — Veri Artırma

# ── ImageDataGenerator ─────────────────────────────────────────
# Gerçek zamanlı (on-the-fly) augmentation yapar. Bellekte üretilir.

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=40,        # 20 yerine 40 (daha fazla döndürme)
    width_shift_range=0.3,    # 0.2 yerine 0.3 (aracı kaydırma)
    height_shift_range=0.3,   # 0.2 yerine 0.3
    shear_range=0.3,          # Eğme (perspektif kazandırır)
    zoom_range=0.3,           # Zoom miktarını artır
    horizontal_flip=True,     # Aracın yönünü değiştir
    fill_mode='nearest'
)

# ÖNEMLİ: Val ve test için augmentation YAPMA!
val_datagen = ImageDataGenerator()   # Hiçbir dönüşüm yok

# Generator nesneleri — model.fit içinde çağrıldıkça batch üretir
train_gen = train_datagen.flow(
    X_train, y_train,
    batch_size = BATCH_SIZE,
    seed       = SEED
)
val_gen = val_datagen.flow(
    X_val, y_val,
    batch_size = BATCH_SIZE,
    shuffle    = False   # Doğrulamada karıştırma gerekmez
)

# ── Augmentation Sonuçlarını Görselleştir ─────────────────────
sample = X_train[0:1]   # İlk eğitim görüntüsü
aug_gen = train_datagen.flow(sample, batch_size=1)

fig, axes = plt.subplots(2, 6, figsize=(16, 6))
fig.suptitle('Augmentation Örnekleri — Sentetik Aracın Farklı Varyasyonları',
             fontsize=12, fontweight='bold')

axes[0, 0].imshow(sample[0])
axes[0, 0].set_title('ORİJİNAL', fontsize=9, color='green', fontweight='bold')
axes[0, 0].axis('off')

for i, ax in enumerate(list(axes.flat[1:11])):
    aug_img = next(aug_gen)[0]
    ax.imshow(np.clip(aug_img, 0, 1))
    ax.set_title(f'Aug #{i+1}', fontsize=8)
    ax.axis('off')

axes[1, 5].axis('off')
plt.tight_layout()
plt.show()

print("\nGözlem: Her kaporta görüntüsü ışık, açı ve konum olarak biraz farklı ama içeriği aynı.")
print("Model her epoch'ta bu farklı varyasyonları gördüğü için hasarı ezberleyemez, gerçekten öğrenmek zorunda kalır.")

## 6. Evrişim (Convolution) — Teorik Açıklama

# ── 6. Evrişimi Elle Hesaplayarak Anla (Hasar Tespiti) ────────
# Modelin kaportadaki bir "çiziği" nasıl bulduğunu adım adım görelim

import numpy as np

# 5×5 Yapay Görüntü (Sanki bir araç kapısı)
# 1 ve 2'ler: Pürüzsüz boya (karanlık/gri alanlar)
# 8 ve 9'lar: Kaportadaki dikey, parlayan derin çizik
goruntu = np.array([
    [1, 1, 9, 1, 2],
    [2, 1, 8, 2, 1],
    [1, 2, 9, 1, 1],
    [1, 1, 8, 2, 2],
    [2, 1, 9, 1, 1]
], dtype=np.float32)

# 3×3 Dikey Çizik (Çizgi) Algılama Filtresi
# Ortası yüksek pozitif (çiziği arar), yanları negatif (çiziğin etrafındaki düzlüğü arar)
filtre = np.array([
    [-1,  2, -1],
    [-1,  2, -1],
    [-1,  2, -1]
], dtype=np.float32)

# Elle evrişim — 'valid' padding (kenar ekleme yok)
H, W = goruntu.shape
k    = filtre.shape[0]
cikis = np.zeros((H - k + 1, W - k + 1))

for i in range(H - k + 1):
    for j in range(W - k + 1):
        bolge      = goruntu[i:i+k, j:j+k]   # 3×3 bölge al (kaportada gezin)
        cikis[i,j] = np.sum(bolge * filtre)  # Nokta çarpımı (Örtüşüyor mu?)

print("Giriş görüntüsü (5×5 Kaporta Parçası - Ortada çizik var):")
print(goruntu.astype(int))

print("\nFiltre (3×3 — Dikey Çizik Dedektörü):")
print(filtre.astype(int))

print("\nEvrişim Çıktısı (3×3 Özellik Haritası):")
print(cikis.astype(int))

print("\nYorum:")
print(" -> Çıktıdaki yüksek pozitif değerler (örneğin 40+), filtrenin o bölgede çiziği tam olarak yakaladığını gösterir.")
print(" -> Negatif değerler, filtrenin çizikle değil düz boyayla veya kenarla karşılaştığı yerlerdir.")
print(" -> CNN ilk katmanlarda işte bu basit çizik/göçük filtrelerini öğrenir!")

# ── 7. MaxPooling'i Görselleştir (Hasar Sinyalini Korumak) ────
import numpy as np
import matplotlib.pyplot as plt

# 4x4 Yapay Özellik Haritası (Örn: Conv2D katmanından çıkmış)
# 0, 1, 2: Hasarsız düz kaporta bölgeleri
# 8, 9: Hasar (çizik/göçük) tespit edilen piksellerin güçlü sinyalleri
ornek = np.array([
    [1, 2, 0, 1],
    [0, 8, 1, 0],
    [1, 0, 9, 2],
    [0, 1, 2, 1]
], dtype=np.float32)

fig, axes = plt.subplots(1, 2, figsize=(9, 4.5))
fig.suptitle('MaxPooling2D (2×2) — Hasar Sinyalini Korumak ve Boyut Küçültmek', fontsize=12, fontweight='bold')

# Giriş
axes[0].imshow(ornek, cmap='Blues', vmin=0, vmax=10)
for i in range(4):
    for j in range(4):
        axes[0].text(j, i, str(int(ornek[i,j])),
                     ha='center', va='center', fontsize=16, fontweight='bold')
# 2×2 pencere ızgaraları
for i in [0, 2]:
    for j in [0, 2]:
        rect = plt.Rectangle((j-0.5, i-0.5), 2, 2,
                              fill=False, edgecolor='red', linewidth=2)
        axes[0].add_patch(rect)
axes[0].set_title('Giriş (4×4) — Kırmızı: 2×2 Pencereler')
axes[0].axis('off')

# Çıkış (Her 2x2 penceredeki en yüksek sinyali al)
# [1,2; 0,8] -> max: 8
# [0,1; 1,0] -> max: 1
# [1,0; 0,1] -> max: 1
# [9,2; 2,1] -> max: 9
cikis_pool = np.array([[8, 1], [1, 9]], dtype=np.float32)

axes[1].imshow(cikis_pool, cmap='Oranges', vmin=0, vmax=10)
for i in range(2):
    for j in range(2):
        axes[1].text(j, i, str(int(cikis_pool[i,j])),
                     ha='center', va='center', fontsize=20, fontweight='bold', color='white')
axes[1].set_title('Çıkış (2×2) — Her Penceredeki Maksimum Sinyal')
axes[1].axis('off')

plt.tight_layout()
plt.show()

print("\nYorum:")
print(" -> MaxPooling, giriş boyutunu yarı yarıya küçülterek CPU'daki hesaplama yükünü 4 kat azaltır.")
print(" -> Ancak dikkat edersen, 8 ve 9 gibi yüksek 'hasar sinyallerini' asla kaybetmez, bir sonraki katmana aktarır.")
print(" -> Böylece araç kaportasındaki hasarın tam koordinatını unutsa bile, o bölgede bir hasar olduğu bilgisini korur (Öteleme dayanıklılığı).")

# ── 8. CNN Mimarisi (4 Bloklu Derin Versiyon) ─────────────────
from tensorflow.keras import models, layers

def build_cnn(input_shape=(64, 64, 3)):
    # Türkçe karakterler temizlendi (Arac_Hasar_CNN_Derin)
    model = models.Sequential(name='Arac_Hasar_CNN_Derin')

    # ── GİRİŞ ────────────────────────────────────────────────
    model.add(layers.Input(shape=input_shape))

    # ── BLOK 1: İlkel Özellikler (Kenarlar, renk geçişleri) ──
    model.add(layers.Conv2D(32, (3, 3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.Conv2D(32, (3, 3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2, 2))) # 64x64 → 32x32
    model.add(layers.Dropout(0.25))

    # ── BLOK 2: Orta Seviye Özellikler (Ufak çizikler) ───────
    model.add(layers.Conv2D(64, (3, 3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.Conv2D(64, (3, 3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2, 2))) # 32x32 → 16x16
    model.add(layers.Dropout(0.25))

    # ── BLOK 3: Yüksek Seviye Özellikler (Derin çizikler, göçükler)
    model.add(layers.Conv2D(128, (3, 3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.Conv2D(128, (3, 3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2, 2))) # 16x16 → 8x8
    model.add(layers.Dropout(0.25))

    # ── BLOK 4: Soyut Özellikler (Genel hasar formu) ─────────
    model.add(layers.Conv2D(256, (3, 3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2, 2))) # 8x8 → 4x4
    model.add(layers.Dropout(0.25))

    # ── SINIFLANDIRICI BAŞ ────────────────────────────────────
    model.add(layers.GlobalAveragePooling2D())

    model.add(layers.Dense(256, activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.Dropout(0.50))

    model.add(layers.Dense(64, activation='relu'))
    model.add(layers.Dropout(0.30))

    model.add(layers.Dense(1, activation='sigmoid'))

    return model

# Modeli oluştur ve belleğe al
cnn_model = build_cnn(input_shape=(IMG_SIZE, IMG_SIZE, 3))
cnn_model.summary()

# ── 9. Transfer Learning — VGG16 ile Hasar Tespiti ────────────

def build_transfer_model(input_shape=(64, 64, 3)):
    """
    VGG16 tabanlı transfer learning modeli.
    CPU optimizasyonu için giriş boyutu 64x64'e ayarlanmıştır.
    """
    # ── Temel Model (VGG16'nın Gövdesi) ────────────────────────
    # Eğer daha önce inmediyse yaklaşık 50MB'lık ağırlık dosyasını indirecektir.
    base = VGG16(
        weights     = 'imagenet',  # ImageNet'in devasa bilgisini kullan
        include_top = False,       # Orijinal 1000 sınıflı başı atıyoruz
        input_shape = input_shape
    )
    print(f"VGG16 katman sayısı: {len(base.layers)}")

    # Çok yer kaplamaması için mimari yazdırma kısmını şimdilik kapatabilirsin
    # veya orijinal kodundaki gibi bırakabilirsin.

    # VGG16'nın kendi bilgilerini bozmamak için önce gövdeyi "donduruyoruz"
    base.trainable = False
    print(f"\nEğitilebilir ağırlık (Sadece baş kısım): {sum(tf.size(w).numpy() for w in base.trainable_weights):,}")

    # ── Özel Sınıflandırıcı Baş (Bizim Hasar Dedektörümüz) ─────
    inputs  = keras.Input(shape=input_shape)
    x       = base(inputs, training=False)   # Gövdeden geçir
    x       = layers.GlobalAveragePooling2D()(x) # Özellikleri özetle
    x       = layers.Dense(256, activation='relu')(x)
    x       = layers.BatchNormalization()(x)
    x       = layers.Dropout(0.50)(x)

    # Çıkış: Tek nöron. < 0.5 Hasarsız, >= 0.5 Hasarlı
    outputs = layers.Dense(1, activation='sigmoid')(x)

    model = keras.Model(inputs, outputs, name='Transfer_VGG16_Hasar')
    return model, base

# Transfer Learning modelimizi oluşturup belleğe alıyoruz
tl_model, base_model = build_transfer_model((IMG_SIZE, IMG_SIZE, 3))
tl_model.summary()

## 10. Kayıp Fonksiyonu ve Optimizer

# ── 10. Kayıp Fonksiyonu ve Optimizer (Derleme) ───────────────



print("1. Kendi kurduğumuz CNN modeli derleniyor...")
cnn_model.compile(
    optimizer = optimizers.Adam(learning_rate=1e-3),
    loss      = 'binary_crossentropy',
    metrics   = ['accuracy',
                 keras.metrics.Precision(name='precision'),
                 keras.metrics.Recall(name='recall')]
)

print("2. Transfer Learning (VGG16) modeli derleniyor...")
# Eğer tl_model tanımlı değilse hata vermesin diye ufak bir kontrol ekledik:
try:
    tl_model.compile(
        optimizer = optimizers.Adam(learning_rate=1e-3),
        loss      = 'binary_crossentropy',
        metrics   = ['accuracy',
                     keras.metrics.Precision(name='precision'),
                     keras.metrics.Recall(name='recall')]
    )
    print("✅ Her iki model de başarıyla derlendi ve eğitime (Fit) hazır!")
except NameError:
    print("⚠️ tl_model henüz tanımlanmamış, ama cnn_model eğitime hazır. Sadece cnn_model ile devam edebilirsin!")

## 11. Callback'ler — Akıllı Eğitim Kontrolü

# ── 11. CNN Callback'leri (Akıllı Eğitim Kontrolcüleri) ────────
# Toplam epoch sayımız 15 olduğu için bekleme sürelerini kısalttık.

cnn_callbacks = [

    callbacks.EarlyStopping(
        monitor             = 'val_accuracy',
        # Doğrulama accuracy'sini izle

        patience            = 4,
        # 8 yerine 4'e düşürdük. 4 epoch iyileşme olmazsa eğitimi durdur.

        restore_best_weights= True,
        # Durduğunda en iyi epoch'taki (en iyi hasar tespiti yapan) ağırlıklara dön

        verbose             = 1
    ),

    callbacks.ReduceLROnPlateau(
        monitor  = 'val_loss',
        factor   = 0.5,       # Yeni LR = Eski LR × 0.5
        patience = 2,         # Tıkanmayı fark etmesi için 4 yerine 2 epoch bekle
        min_lr   = 1e-6,      # LR bu değerden küçük olamaz
        verbose  = 1
    ),

    callbacks.ModelCheckpoint(
        filepath       = 'best_hasar_tespit_cnn.keras', # Dosya adını güncelledik
        monitor        = 'val_accuracy',
        save_best_only = True,   # Sadece iyileşme olursa kaydet
        verbose        = 0
    )
]

print("Callback'ler Araç Hasar Tespiti için hazır:")
print("  ✓ EarlyStopping     — patience=4, en iyi ağırlıklar korunacak")
print("  ✓ ReduceLROnPlateau — factor=0.5, patience=2")
print("  ✓ ModelCheckpoint   — best_hasar_tespit_cnn.keras")

## 12. Eğitim Döngüsü

import tensorflow as tf
from tensorflow.keras import backend as K

# 1. TensorFlow'un hafızasını (arka planı) tamamen temizle
K.clear_session()
print("1. Keras arka plan hafızası temizlendi.")

# 2. Modeli baştan, tertemiz bir şekilde kur (Önceki hücrede tanımladığımız build_cnn fonksiyonu ile)
cnn_model = build_cnn(input_shape=(IMG_SIZE, IMG_SIZE, 3))

# 3. Modeli yeniden derle
cnn_model.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss      = 'binary_crossentropy',
    metrics   = ['accuracy',
                 tf.keras.metrics.Precision(name='precision'),
                 tf.keras.metrics.Recall(name='recall')]
)
print("2. Model sıfırdan kuruldu ve derlendi.")

# 4. Jeneratörleri sıfırla (Kaldığı yerden devam etmeye çalışıp hata vermemesi için)
train_gen = train_datagen.flow(X_train, y_train, batch_size=BATCH_SIZE, seed=SEED)
val_gen   = val_datagen.flow(X_val, y_val, batch_size=BATCH_SIZE, shuffle=False)
print("3. Veri jeneratörleri sıfırlandı.")

# 5. Eğitimi Başlat
print("\n" + "=" * 60)
print("  Araç Hasar Tespiti — Temiz Hafıza İle Eğitim Başlıyor")
print("=" * 60)

cnn_history = cnn_model.fit(
    train_gen,
    epochs          = EPOCHS,
    validation_data = val_gen,
    callbacks       = cnn_callbacks,
    verbose         = 1
)

print("\nEğitim tamamlandı! 🎉")
best_val_acc = max(cnn_history.history['val_accuracy'])
print(f"En İyi Doğrulama Doğruluğu (Validation Accuracy): {best_val_acc:.4f}")

# ── Transfer Learning (VGG16) Eğitimi ─────────────────────────
import tensorflow as tf
from tensorflow.keras import backend as K

# 1. TensorFlow belleğini tamamen temizle (Tüm eski optimizasyon kalıntılarını siler)
K.clear_session()
print("✅ Bellek temizlendi, eski optimizasyon hataları sıfırlandı.")

# 2. VGG16 modelini yeniden oluştur
# (Hücrenin içinde build_transfer_model fonksiyonunun tanımlı olduğundan emin ol)
tl_model, base_model = build_transfer_model((IMG_SIZE, IMG_SIZE, 3))

# 3. Derle (Compile)
tl_model.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss      = 'binary_crossentropy',
    metrics   = ['accuracy',
                 tf.keras.metrics.Precision(name='precision'),
                 tf.keras.metrics.Recall(name='recall')]
)

# 4. Eğitim (Fit) - Artık hata vermeyecektir
print("\n" + "=" * 60)
print("  Transfer Learning — Eğitim Başlıyor (Temiz Hafıza)")
print("=" * 60)

tl_hist1 = tl_model.fit(
    train_gen,
    epochs          = max(5, EPOCHS // 3),
    validation_data = val_gen,
    callbacks       = tl_callbacks,
    verbose         = 1
)
import tensorflow.keras.optimizers as optimizers

# CPU optimizasyonu için sabırsız (düşük patience) callback'ler kullanıyoruz.
tl_callbacks = [
    callbacks.EarlyStopping(monitor='val_accuracy', patience=3,
                             restore_best_weights=True, verbose=1),
    callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                                 patience=2, verbose=1)
]

print("=" * 60)
print("  Transfer Learning — Aşama 1: Sadece Sınıflandırıcı Başı Eğit")
print("=" * 60)

# Aşama 1: VGG16 gövdesi donuk, sadece bizim eklediğimiz baş (Dense) katmanları öğreniyor
tl_hist1 = tl_model.fit(
    train_gen,
    epochs          = max(5, EPOCHS // 3), # 15 epoch için yaklaşık 5 tur dönecek
    validation_data = val_gen,
    callbacks       = tl_callbacks,
    verbose         = 1
)

# ── Fine-Tuning (İnce Ayar) ──────────────────────────────────
print("\n" + "=" * 60)
print("  Aşama 2: Fine-Tuning (VGG16'nın son 4 katmanı hasar tespiti için açılıyor)")
print("=" * 60)

base_model.trainable = True
# Tüm katmanları önce dondur, sonra sadece son 4 katmanı aç
for layer in base_model.layers[:-4]:
    layer.trainable = False

acik = sum(1 for l in base_model.layers if l.trainable)
print(f"VGG16'da açık katman sayısı: {acik} / {len(base_model.layers)}")

# Fine-tuning için çok daha düşük LR (Learning Rate) kullan!
# Yüksek LR, VGG16'nın daha önce öğrendiği değerli kaporta/metal bilgilerini ezer (catastrophic forgetting)
tl_model.compile(
    optimizer = optimizers.Adam(learning_rate=1e-5),   # 1e-3'ün 100'de biri (Çok yavaş ve dikkatli adımlar)
    loss      = 'binary_crossentropy',
    metrics   = ['accuracy',
                 keras.metrics.Precision(name='precision'),
                 keras.metrics.Recall(name='recall')]
)

# Aşama 2: Açılan son 4 katman ve bizim baş kısmımız birlikte eğitiliyor
tl_hist2 = tl_model.fit(
    train_gen,
    epochs          = max(5, EPOCHS // 3), # Yaklaşık 5 tur daha
    validation_data = val_gen,
    callbacks       = tl_callbacks,
    verbose         = 1
)

print("\nTransfer Learning (VGG16) ile Araç Hasar Tespiti eğitimi tamamlandı! 🎉")

## 13. Değerlendirme Metrikleri — Detaylı Açıklama

from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, roc_curve, classification_report, confusion_matrix
import seaborn as sns

def evaluate_model(model, X_test, y_test, model_name='Model'):
    """Hasar tespiti için kapsamlı değerlendirme."""
    print(f"\n{'='*60}")
    print(f"  {model_name} — Test Seti Değerlendirmesi")
    print(f"{'='*60}")

    # Olasılık ve etiket tahmini
    y_prob = model.predict(X_test, verbose=0).flatten()
    y_pred = (y_prob >= 0.5).astype(int)

    # Temel metrikler
    acc = accuracy_score(y_test, y_pred)
    f1  = f1_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_prob)

    print(f"  Accuracy  : {acc:.4f}  ({acc*100:.1f}% doğru tahmin)")
    print(f"  F1 Score  : {f1:.4f}")
    print(f"  ROC-AUC   : {auc:.4f}  (1.0=mükemmel, 0.5=rastgele)")

    # Detaylı sınıflandırma raporu
    print(f"\n  Sınıflandırma Raporu:")
    print(classification_report(y_test, y_pred, target_names=CLASSES, digits=4))

    # Görselleştirme
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    fig.suptitle(f'{model_name} — Test Seti Sonuçları', fontsize=13, fontweight='bold')

    # 1. Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=CLASSES, yticklabels=CLASSES,
                linewidths=0.5, ax=axes[0], annot_kws={'size': 14})
    axes[0].set_xlabel('TAHMİN', fontweight='bold')
    axes[0].set_ylabel('GERÇEK', fontweight='bold')
    axes[0].set_title('Karışıklık Matrisi')

    # Yüzdeli yorumlama
    tn, fp, fn, tp = cm.ravel()
    print(f"  Confusion Matrix Analizi:")
    print(f"    TN (Doğru Hasarsız) : {tn:4d}")
    print(f"    FP (Yanlış Hasarlı) : {fp:4d}  ← Hasarsız aracı hasarlı sandık!")
    print(f"    FN (Yanlış Hasarsız): {fn:4d}  ← Hasarlı aracı sağlam sandık!")
    print(f"    TP (Doğru Hasarlı)  : {tp:4d}")

    # 2. ROC Eğrisi
    fpr, tpr, thresholds = roc_curve(y_test, y_prob)
    axes[1].plot(fpr, tpr, color='blue', linewidth=2, label=f'AUC = {auc:.4f}')
    axes[1].plot([0, 1], [0, 1], 'k--', linewidth=1, label='Rastgele (AUC=0.5)')
    axes[1].fill_between(fpr, tpr, alpha=0.15, color='blue')
    axes[1].set_xlabel('Yanlış Pozitif Oranı (FPR)')
    axes[1].set_ylabel('Doğru Pozitif Oranı (TPR)')
    axes[1].set_title('ROC Eğrisi')
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    # 3. Tahmin Olasılığı Dağılımı
    axes[2].hist(y_prob[y_test==0], bins=25, alpha=0.7,
                 color='#FF6B6B', label='Hasarsız (0)', edgecolor='white')
    axes[2].hist(y_prob[y_test==1], bins=25, alpha=0.7,
                 color='#4ECDC4', label='Hasarlı (1)', edgecolor='white')
    axes[2].axvline(0.5, color='black', linestyle='--', linewidth=2, label='Eşik=0.5')
    axes[2].set_xlabel('Hasarlı Olasılığı (model çıkışı)')
    axes[2].set_ylabel('Frekans')
    axes[2].set_title('Tahmin Dağılımı')
    axes[2].legend()
    axes[2].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()
    return y_prob, y_pred

# ── Modelleri Değerlendir ─────────────────────────────────────
cnn_prob, cnn_pred = evaluate_model(cnn_model, X_test, y_test, 'CNN (Scratch)')
tl_prob,  tl_pred  = evaluate_model(tl_model,  X_test, y_test, 'VGG16 (Transfer)')

## 14. Eğitim Geçmişi Görselleştirme

def plot_history(history, title):
    """
    Accuracy ve Loss grafiklerini yan yana çizer.
    Eğitim ve doğrulama eğrilerinin analizi:
    - İki eğri birbirine yakın → Hasar örüntülerini iyi genelliyor
    - Eğitim yüksek, doğrulama düşük → Kaportayı ezberliyor (Overfitting)
    - İkisi de düşük → Model hasarı ayırt edemiyor (Underfitting)
    """
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle(title, fontsize=13, fontweight='bold')
    epochs_range = range(1, len(history.history['accuracy']) + 1)

    # ── Accuracy ──────────────────────────────────────────────
    ax = axes[0]
    ax.plot(epochs_range, history.history['accuracy'],
            color='#2196F3', linewidth=2, label='Eğitim', marker='o', markersize=3)
    ax.plot(epochs_range, history.history['val_accuracy'],
            color='#FF5722', linewidth=2, label='Doğrulama',
            marker='s', markersize=3, linestyle='--')

    # En iyi epoch'u işaretle
    best_epoch = np.argmax(history.history['val_accuracy']) + 1
    best_val   = max(history.history['val_accuracy'])
    ax.axvline(best_epoch, color='green', linestyle=':', linewidth=1.5,
               label=f'En İyi Epoch: {best_epoch}')
    ax.annotate(f'{best_val:.3f}', xy=(best_epoch, best_val),
                xytext=(best_epoch + 0.5, best_val - 0.05), fontsize=9, color='green')

    ax.set_title('Doğruluk (Accuracy)', fontweight='bold')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Accuracy')
    ax.set_ylim([0, 1.05])
    ax.legend()
    ax.grid(True, alpha=0.3)

    # ── Loss ──────────────────────────────────────────────────
    ax = axes[1]
    ax.plot(epochs_range, history.history['loss'],
            color='#2196F3', linewidth=2, label='Eğitim', marker='o', markersize=3)
    ax.plot(epochs_range, history.history['val_loss'],
            color='#FF5722', linewidth=2, label='Doğrulama',
            marker='s', markersize=3, linestyle='--')

    ax.set_title('Kayıp (Loss)', fontweight='bold')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Binary Cross-Entropy')
    ax.legend()
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

    # Overfitting analizi
    son_train = history.history['accuracy'][-1]
    son_val   = history.history['val_accuracy'][-1]
    fark      = son_train - son_val
    print(f"\nSon epoch — Eğitim: {son_train:.4f} | Doğrulama: {son_val:.4f}")
    print(f"Fark (overfitting göstergesi): {fark:.4f}")

    if fark > 0.10:
        print("⚠️  Overfitting var! Model eğitimdeki çizikleri ezberledi, yeni aracı tanıyamaz.")
    elif fark < 0.02:
        print("✅  Çok iyi genelleme! Model hasar örüntülerini öğrendi.")
    else:
        print("🟡  Hafif overfitting — kabul edilebilir aralıkta.")

# Modellerin geçmişini görselleştir
plot_history(cnn_history, 'Araç Hasar Tespiti — Eğitim Geçmişi')

# ── 14. Model Karşılaştırması — Görselleştirme ─────────────────
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

# Modellerimizin performans metriklerini listeliyoruz
model_isimleri = ['CNN\nScratch', 'Transfer\nVGG16']
acclari = [accuracy_score(y_test, cnn_pred), accuracy_score(y_test, tl_pred)]
f1lari  = [f1_score(y_test, cnn_pred),       f1_score(y_test, tl_pred)]
auclari = [roc_auc_score(y_test, cnn_prob),  roc_auc_score(y_test, tl_prob)]

# Görselleştirme
fig, axes = plt.subplots(1, 3, figsize=(14, 5))
fig.suptitle('Model Karşılaştırması — Araç Hasar Tespiti Test Sonuçları', fontsize=13, fontweight='bold')

renkler = ['#667eea', '#f093fb'] # Mavi ve mor tonları
for ax, degerler, baslik in zip(
        axes, [acclari, f1lari, auclari],
        ['Accuracy (Doğruluk)', 'F1 Score (Denge)', 'ROC-AUC (Güven)']):
    bars = ax.bar(model_isimleri, degerler, color=renkler, edgecolor='white', linewidth=1.5)
    ax.set_title(baslik, fontweight='bold')
    ax.set_ylim([0, 1.15])
    ax.grid(axis='y', alpha=0.3)

    # Sütunların üzerine değerleri yaz
    for bar, deger in zip(bars, degerler):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + 0.02,
                f'{deger:.3f}', ha='center', fontsize=12, fontweight='bold')

plt.tight_layout()
plt.show()

# Metinsel Karşılaştırma Tablosu
print("\nFinal Karşılaştırma Tablosu:")
print(f"{'Model':20s} {'Accuracy':>10} {'F1':>10} {'ROC-AUC':>10}")
print("-" * 55)
print(f"{'CNN Scratch':20s} {acclari[0]:>10.4f} {f1lari[0]:>10.4f} {auclari[0]:>10.4f}")
print(f"{'Transfer VGG16':20s} {acclari[1]:>10.4f} {f1lari[1]:>10.4f} {auclari[1]:>10.4f}")

## 15. Tek Görüntü Üzerinde Tahmin

def tahmin_et(model, goruntu_veya_yol, esik=0.5, model_adi='Model'):
    """
    Tek görüntü üzerinde tahmin yap ve görselleştir.
    """
    # ── Görüntü Hazırlama ──────────────────────────────────────
    if isinstance(goruntu_veya_yol, str):
        img_bgr = cv2.imread(goruntu_veya_yol)
        if img_bgr is None:
            raise FileNotFoundError(f"Görüntü okunamadı: {goruntu_veya_yol}")
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        img_res = cv2.resize(img_rgb, (IMG_SIZE, IMG_SIZE))
        img     = img_res.astype(np.float32) / 255.0
    else:
        img = goruntu_veya_yol

    # ── Tahmin ────────────────────────────────────────────────
    batch = img[np.newaxis, ...]
    olasilik = model.predict(batch, verbose=0)[0, 0]

    etiket = 1 if olasilik >= esik else 0
    sinif  = CLASSES[etiket]
    guven  = olasilik if etiket == 1 else 1 - olasilik

    # ── Görselleştir ───────────────────────────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    fig.suptitle(f'{model_adi} Tahmini', fontsize=12, fontweight='bold')

    axes[0].imshow(img)
    renk  = '#FF6B6B' if etiket == 0 else '#4ECDC4' # Hasarsız kırmızı, Hasarlı turkuaz
    emoji = '✅' if etiket == 0 else '⚠️' # Hasarsız tik, Hasarlı uyarı
    axes[0].set_title(f'{emoji} {sinif.upper()} — Güven: {guven*100:.1f}%',
                      fontsize=13, fontweight='bold', color=renk)
    axes[0].axis('off')

    # Olasılık çubuğu
    categories = ['Hasarsız\n(0)', 'Hasarlı\n(1)']
    values     = [1 - olasilik, olasilik]
    renkler    = ['#FF6B6B', '#4ECDC4']
    bars = axes[1].bar(categories, values, color=renkler, edgecolor='white', linewidth=2)
    axes[1].axhline(0.5, color='black', linestyle='--', linewidth=1.5, label='Eşik = 0.5')
    axes[1].set_ylim([0, 1.1])
    axes[1].set_ylabel('Olasılık')
    axes[1].set_title('Hasar Olasılık Dağılımı')
    axes[1].legend()
    axes[1].grid(axis='y', alpha=0.3)
    for bar, val in zip(bars, values):
        axes[1].text(bar.get_x() + bar.get_width()/2, val + 0.02,
                     f'{val:.3f}', ha='center', fontweight='bold', fontsize=11)

    plt.tight_layout()
    plt.show()

    print(f"Tahmin   : {sinif.upper()}")
    print(f"Güven    : {guven*100:.2f}%")
    return sinif, olasilik


# ── Test Setinden Rastgele Örnekler ───────────────────────────
print("Test setinden rastgele araç örnekleri üzerinde tahminler:\n")
for i in range(3):
    idx = random.randint(0, len(X_test)-1)
    print(f"Gerçek Durum: {CLASSES[y_test[idx]].upper()}")
    tahmin_et(cnn_model, X_test[idx], model_adi='CNN Hasar Dedektörü')
    print("-" * 40)

# ── 15. Modelleri Kaydet ──────────────────────────────────────
# Modellerini diskte kalıcı hale getiriyoruz
cnn_model.save('arac_hasar_cnn_final.keras')
tl_model.save('arac_hasar_vgg16_final.keras')

print("✅ Modeller başarıyla kaydedildi:")
print("   - arac_hasar_cnn_final.keras")
print("   - arac_hasar_vgg16_final.keras")

# ── 16. Final Sonuç Tablosu ──────────────────────────────────
print("\n" + "=" * 60)
print("  FİNAL KARŞILAŞTIRMA TABLOSU")
print("=" * 60)
print(f"  {'Model':20s} {'Accuracy':>10} {'F1':>10} {'AUC':>10}")
print("-" * 60)
print(f"  {'CNN Scratch':20s} {accuracy_score(y_test, cnn_pred):>10.4f} "
      f"{f1_score(y_test, cnn_pred):>10.4f} {roc_auc_score(y_test, cnn_prob):>10.4f}")
print(f"  {'Transfer VGG16':20s} {accuracy_score(y_test, tl_pred):>10.4f} "
      f"{f1_score(y_test, tl_pred):>10.4f} {roc_auc_score(y_test, tl_prob):>10.4f}")
print("=" * 60)

print("\n🚀 Notebook başarıyla tamamlandı! Araç hasar tespit modelin hazır.")
print("Bir sonraki adımda, gerçek hayattan (Kaggle/Dataset) gerçek hasarlı araç fotoğrafları yükleyerek sistemini sahada test edebilirsin!")